"""Hand-seeded North End corpus for Sprint 0.

Raw names/descriptions/prices come from official restaurant pages where
published. Giacomo's does not list most à-la-carte prices on its site; those
prices are taken from widely published Yelp menu listings and are tagged
with lower confidence until Phase 1 extraction from the official menu.
Missing prices are left null — never invented.
"""

from __future__ import annotations

from typing import Any

CANONICAL_DISHES: list[dict[str, Any]] = [
    {
        "canonical_dish_id": "LOBSTER_RAVIOLI",
        "canonical_name": "Lobster ravioli",
        "category": "pasta",
        "subcategory": "stuffed",
        "description": "Ravioli filled with lobster.",
        "aliases": ["lobster ravioli", "ravioli di astice"],
    },
    {
        "canonical_dish_id": "SQUASH_RAVIOLI",
        "canonical_name": "Butternut squash ravioli",
        "category": "pasta",
        "subcategory": "stuffed",
        "description": "Ravioli filled with squash or pumpkin.",
        "aliases": ["butternut squash ravioli", "pumpkin ravioli", "pumpkin tortellini"],
    },
    {
        "canonical_dish_id": "CHICKEN_PARMIGIANA",
        "canonical_name": "Chicken parmigiana",
        "category": "italian_american",
        "subcategory": "parm",
        "description": "Breaded chicken with tomato and mozzarella.",
        "aliases": ["chicken parm", "chicken parmesan", "pollo parmigiana"],
    },
    {
        "canonical_dish_id": "EGGPLANT_PARMIGIANA",
        "canonical_name": "Eggplant parmigiana",
        "category": "italian_american",
        "subcategory": "parm",
        "description": "Layered eggplant with tomato and cheese.",
        "aliases": ["eggplant parm", "eggplant rollatini", "melanzane"],
    },
    {
        "canonical_dish_id": "MEATBALLS",
        "canonical_name": "Meatballs",
        "category": "italian_american",
        "subcategory": "meat",
        "description": "Beef or mixed meatballs, typically with ricotta or marinara.",
        "aliases": ["polpette", "homemade meatballs"],
    },
    {
        "canonical_dish_id": "FRUTTI_DI_MARE",
        "canonical_name": "Frutti di mare",
        "category": "pasta",
        "subcategory": "seafood",
        "description": "Mixed seafood pasta.",
        "aliases": ["frutti di mare linguine", "seafood linguine", "zuppa di pesce"],
    },
    {
        "canonical_dish_id": "SEAFOOD_PASTA",
        "canonical_name": "Seafood pasta",
        "category": "pasta",
        "subcategory": "seafood",
        "description": "Pasta with one or more seafood proteins.",
        "aliases": ["shrimp linguine", "scallops linguine", "mussels linguine", "lobster pasta"],
    },
    {
        "canonical_dish_id": "AMATRICIANA",
        "canonical_name": "Amatriciana",
        "category": "pasta",
        "subcategory": "sauce",
        "description": "Tomato, guanciale or pancetta, pecorino.",
        "aliases": ["garganelli amatriciana"],
    },
    {
        "canonical_dish_id": "POMODORO",
        "canonical_name": "Pomodoro",
        "category": "pasta",
        "subcategory": "sauce",
        "description": "Tomato and basil pasta.",
        "aliases": ["al pomodoro", "spaghettoni al pomodoro"],
    },
    {
        "canonical_dish_id": "MARGHERITA",
        "canonical_name": "Margherita pizza",
        "category": "pizza",
        "subcategory": "classic",
        "description": "Tomato, mozzarella, basil.",
        "aliases": ["pizza margherita"],
    },
    {
        "canonical_dish_id": "CHEESE_PIZZA",
        "canonical_name": "Cheese pizza",
        "category": "pizza",
        "subcategory": "classic",
        "description": "Plain cheese / original pie.",
        "aliases": ["original pizza", "cheese pie"],
    },
    {
        "canonical_dish_id": "WHITE_PIZZA",
        "canonical_name": "White pizza",
        "category": "pizza",
        "subcategory": "white",
        "description": "Pizza without red sauce.",
        "aliases": ["quattro formaggio", "vegetarian primavera"],
    },
    {
        "canonical_dish_id": "CANNOLI",
        "canonical_name": "Cannoli",
        "category": "dessert",
        "subcategory": "pastry",
        "description": "Fried pastry shell with sweet ricotta or custard.",
        "aliases": ["cannoli siciliani"],
    },
    {
        "canonical_dish_id": "TIRAMISU",
        "canonical_name": "Tiramisu",
        "category": "dessert",
        "subcategory": "cake",
        "description": "Espresso-soaked ladyfingers and mascarpone.",
        "aliases": ["tiramisú"],
    },
    {
        "canonical_dish_id": "LOBSTER_TAIL_PASTRY",
        "canonical_name": "Lobster tail pastry",
        "category": "dessert",
        "subcategory": "pastry",
        "description": "Sfogliatella-style shell filled with cream; not seafood.",
        "aliases": ["lobster tail", "code d'aragosta"],
    },
    {
        "canonical_dish_id": "SFOGLIATELLE",
        "canonical_name": "Sfogliatelle",
        "category": "dessert",
        "subcategory": "pastry",
        "description": "Layered shell pastry, typically ricotta.",
        "aliases": ["sfogliatella"],
    },
    {
        "canonical_dish_id": "RICOTTA_PIE",
        "canonical_name": "Ricotta pie",
        "category": "dessert",
        "subcategory": "pie",
        "description": "Italian ricotta pie.",
        "aliases": ["pizza di ricotta", "ricotta pie slice"],
    },
    {
        "canonical_dish_id": "OCTOPUS",
        "canonical_name": "Octopus",
        "category": "seafood",
        "subcategory": "cephalopod",
        "description": "Octopus, grilled or roasted.",
        "aliases": ["spanish octopus", "polpo"],
    },
    {
        "canonical_dish_id": "CALAMARI",
        "canonical_name": "Calamari",
        "category": "seafood",
        "subcategory": "cephalopod",
        "description": "Fried or sautéed squid.",
        "aliases": ["fried calamari", "calamari fritti"],
    },
    {
        "canonical_dish_id": "CIOPPINO",
        "canonical_name": "Cioppino",
        "category": "seafood",
        "subcategory": "stew",
        "description": "Seafood stew in tomato/brodo.",
        "aliases": ["north end cioppino", "brodetto"],
    },
    {
        "canonical_dish_id": "LOBSTER_ROLL",
        "canonical_name": "Lobster roll",
        "category": "seafood",
        "subcategory": "sandwich",
        "description": "Lobster meat on a bun, hot butter or cold mayo.",
        "aliases": ["maine lobster roll"],
    },
    {
        "canonical_dish_id": "OYSTERS",
        "canonical_name": "Oysters",
        "category": "seafood",
        "subcategory": "raw_bar",
        "description": "Oysters on the half shell.",
        "aliases": ["east coast oysters", "west coast oysters"],
    },
    {
        "canonical_dish_id": "ARANCINI",
        "canonical_name": "Arancini",
        "category": "antipasti",
        "subcategory": "fried",
        "description": "Fried risotto balls.",
        "aliases": ["rice balls"],
    },
    {
        "canonical_dish_id": "BURRATA",
        "canonical_name": "Burrata",
        "category": "antipasti",
        "subcategory": "cheese",
        "description": "Fresh burrata.",
        "aliases": ["burrata caprese"],
    },
    {
        "canonical_dish_id": "CARBONARA",
        "canonical_name": "Carbonara",
        "category": "pasta",
        "subcategory": "sauce",
        "description": "Egg, pecorino, guanciale, pepper.",
        "aliases": ["spaghetti carbonara"],
    },
]


def item(
    raw_name: str,
    *,
    section: str,
    raw_description: str | None = None,
    raw_price_text: str | None = None,
    price: float | None = None,
    canonical_category: str | None = None,
    canonical_dish: str | None = None,
    protein: list[str] | None = None,
    pasta_type: str | None = None,
    sauce: str | None = None,
    preparation: str | None = None,
    ingredients: list[str] | None = None,
    dietary_tags: list[str] | None = None,
    portion: str | None = None,
    size: str | None = None,
    seasonal: bool = False,
    market_price: bool = False,
    confidence: float = 0.92,
) -> dict[str, Any]:
    return {
        "raw_name": raw_name,
        "raw_description": raw_description,
        "raw_price_text": raw_price_text,
        "price": price,
        "menu_section": section,
        "canonical_category": canonical_category,
        "canonical_dish": canonical_dish,
        "protein": protein,
        "pasta_type": pasta_type,
        "sauce": sauce,
        "preparation": preparation,
        "ingredients": ingredients,
        "dietary_tags": dietary_tags,
        "portion": portion,
        "size": size,
        "seasonal": seasonal,
        "market_price": market_price,
        "available": True,
        "normalization_confidence": confidence,
    }


RESTAURANTS: list[dict[str, Any]] = [
    {
        "restaurant_id": "NE_0001",
        "name": "Giacomo's Ristorante",
        "slug": "giacomos-ristorante",
        "address": "355 Hanover Street, Boston, MA 02113",
        "latitude": 42.364591,
        "longitude": -71.053375,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "seafood",
        "official_website": "https://giacomosboston.com/",
        "official_menu_url": "https://giacomosboston.com/menu",
        "photo_url": "/restaurant-photos/giacomos-ristorante.jpg",
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://giacomosboston.com/menu",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v1",
        "items": [
            item(
                "Zuppa di Pesce",
                section="House Special",
                raw_description="Lobster, shrimp, scallops, calamari, clams and mussels over linguine. Dinner for two.",
                raw_price_text="$98",
                price=98,
                canonical_category="pasta",
                canonical_dish="FRUTTI_DI_MARE",
                protein=["lobster", "shrimp", "scallop", "calamari", "clams", "mussels"],
                pasta_type="linguine",
                sauce="red",
                ingredients=["lobster", "shrimp", "scallops", "calamari", "clams", "mussels"],
                portion="dinner for two",
                confidence=0.97,
            ),
            item(
                "Lobster Ravioli",
                section="Ravioli",
                raw_description="Served with diced tomato in a garlic cream sauce.",
                raw_price_text="$29.00",
                price=29,
                canonical_category="pasta",
                canonical_dish="LOBSTER_RAVIOLI",
                protein=["lobster"],
                pasta_type="ravioli",
                sauce="garlic cream",
                ingredients=["lobster", "tomato", "garlic", "cream"],
                confidence=0.86,
            ),
            item(
                "Butternut Squash Ravioli",
                section="Ravioli",
                raw_price_text="$23.00",
                price=23,
                canonical_category="pasta",
                canonical_dish="SQUASH_RAVIOLI",
                pasta_type="ravioli",
                ingredients=["butternut squash"],
                dietary_tags=["vegetarian"],
                confidence=0.86,
            ),
            item(
                "Pumpkin Tortellini",
                section="Ravioli",
                raw_price_text="$23.00",
                price=23,
                canonical_category="pasta",
                canonical_dish="SQUASH_RAVIOLI",
                pasta_type="tortellini",
                ingredients=["pumpkin"],
                dietary_tags=["vegetarian"],
                confidence=0.84,
            ),
            item(
                "Frutti Di Mare Linguine",
                section="Linguine",
                raw_description="Shrimp, scallops, calamari, clams, and mussels. Choice of pesto, red, fra diavolo, giacomo, fracomo, or scampi.",
                raw_price_text="$39.00",
                price=39,
                canonical_category="pasta",
                canonical_dish="FRUTTI_DI_MARE",
                protein=["shrimp", "scallop", "calamari", "clams", "mussels"],
                pasta_type="linguine",
                ingredients=["shrimp", "scallops", "calamari", "clams", "mussels"],
                confidence=0.9,
            ),
            item(
                "Shrimp and Scallops Linguine",
                section="Linguine",
                raw_price_text="$32.00",
                price=32,
                canonical_category="pasta",
                canonical_dish="SEAFOOD_PASTA",
                protein=["shrimp", "scallop"],
                pasta_type="linguine",
                ingredients=["shrimp", "scallops"],
                confidence=0.9,
            ),
            item(
                "Mussels and Clams Linguine",
                section="Linguine",
                raw_price_text="$28.00",
                price=28,
                canonical_category="pasta",
                canonical_dish="SEAFOOD_PASTA",
                protein=["mussels", "clams"],
                pasta_type="linguine",
                ingredients=["mussels", "clams"],
                confidence=0.9,
            ),
            item(
                "Homemade Fusilli",
                section="House Special",
                raw_description="Often served with lobster and shrimp.",
                raw_price_text="$38.00",
                price=38,
                canonical_category="pasta",
                canonical_dish="SEAFOOD_PASTA",
                protein=["lobster", "shrimp"],
                pasta_type="fusilli",
                confidence=0.72,
            ),
            item(
                "Chicken Parmigiana",
                section="Marsalas and Parmigianas",
                raw_description="Breaded chicken covered with mozzarella cheese and marinara sauce. Served with a side of pasta in a marinara sauce.",
                raw_price_text="$24.00",
                price=24,
                canonical_category="italian_american",
                canonical_dish="CHICKEN_PARMIGIANA",
                protein=["chicken"],
                sauce="marinara",
                ingredients=["chicken", "mozzarella", "marinara"],
                confidence=0.88,
            ),
            item(
                "Eggplant Rollatini",
                section="Appetizers",
                raw_description="Stuffed with ricotta, romano and mozzarella.",
                canonical_category="italian_american",
                canonical_dish="EGGPLANT_PARMIGIANA",
                ingredients=["eggplant", "ricotta", "romano", "mozzarella"],
                dietary_tags=["vegetarian"],
                confidence=0.9,
            ),
            item(
                "Fried Calamari",
                section="Appetizers",
                raw_price_text="$18.00",
                price=18,
                canonical_category="seafood",
                canonical_dish="CALAMARI",
                protein=["calamari"],
                preparation="fried",
                confidence=0.93,
            ),
            item(
                "Burrata",
                section="Appetizers",
                raw_price_text="$19.00",
                price=19,
                canonical_category="antipasti",
                canonical_dish="BURRATA",
                dietary_tags=["vegetarian"],
                confidence=0.93,
            ),
            item(
                "Meatballs",
                section="Appetizers",
                raw_price_text="$12.00",
                price=12,
                canonical_category="italian_american",
                canonical_dish="MEATBALLS",
                protein=["beef"],
                confidence=0.9,
            ),
            item(
                "Caprese Salad",
                section="Salads",
                raw_price_text="$16.00",
                price=16,
                canonical_category="antipasti",
                ingredients=["tomato", "mozzarella", "basil"],
                dietary_tags=["vegetarian"],
                confidence=0.9,
            ),
            item(
                "Bruschetta",
                section="Appetizers",
                raw_description="Tomato, basil, oil.",
                canonical_category="antipasti",
                ingredients=["tomato", "basil"],
                dietary_tags=["vegetarian"],
                confidence=0.95,
            ),
        ],
    },
    {
        "restaurant_id": "NE_0002",
        "name": "Neptune Oyster",
        "slug": "neptune-oyster",
        "address": "63 Salem Street, Boston, MA 02113",
        "latitude": 42.36415,
        "longitude": -71.05585,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "seafood",
        "secondary_cuisines": None,
        "official_website": "https://neptuneoyster.com/",
        "official_menu_url": "https://www.neptuneoyster.com/menu",
        "photo_url": "/restaurant-photos/neptune-oyster.jpg",
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://www.neptuneoyster.com/menu",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v1",
        "items": [
            item(
                "Golden Sea Bream",
                section="Crudo",
                raw_description="Honeycrisp Apple • black lava sea salt",
                raw_price_text="18",
                price=18,
                canonical_category="seafood",
                protein=["bream"],
                preparation="crudo",
                ingredients=["sea bream", "honeycrisp apple", "black lava sea salt"],
            ),
            item(
                "Bluefin",
                section="Crudo",
                raw_description="Piri Piri pepitas • Castelvetrano olive",
                raw_price_text="21",
                price=21,
                canonical_category="seafood",
                protein=["tuna"],
                preparation="crudo",
                ingredients=["bluefin tuna", "piri piri pepitas", "castelvetrano olive"],
            ),
            item(
                "Bay Scallop",
                section="Crudo",
                raw_description="Nardello • cucumber • Duxbury sea salt",
                raw_price_text="MKT",
                market_price=True,
                canonical_category="seafood",
                protein=["scallop"],
                preparation="crudo",
                ingredients=["bay scallop", "nardello pepper", "cucumber"],
            ),
            item(
                "Wellfleet Clam Chowder",
                section="Classics",
                raw_description="Salt pork • thyme",
                raw_price_text="15",
                price=15,
                canonical_category="seafood",
                protein=["clams"],
                ingredients=["clam", "salt pork", "thyme"],
            ),
            item(
                "Spanish Octopus",
                section="Classics",
                raw_description="Marcona almond romesco • cauliflower • Espelette oil",
                raw_price_text="22",
                price=22,
                canonical_category="seafood",
                canonical_dish="OCTOPUS",
                protein=["octopus"],
                ingredients=["octopus", "marcona almond", "romesco", "cauliflower"],
            ),
            item(
                "Fried Ipswich Clams",
                section="Classics",
                raw_description="House tartar • lemon",
                raw_price_text="MKT",
                market_price=True,
                canonical_category="seafood",
                protein=["clams"],
                preparation="fried",
                ingredients=["ipswich clams", "tartar", "lemon"],
            ),
            item(
                "Neptune Johnnycake",
                section="Classics",
                raw_description="Honey butter • Boston smoked bluefish • sturgeon caviar",
                raw_price_text="21",
                price=21,
                canonical_category="seafood",
                protein=["bluefish"],
                ingredients=["johnnycake", "honey butter", "smoked bluefish", "sturgeon caviar"],
            ),
            item(
                "Acadian Blue Mussels",
                section="Classics",
                raw_description="Nduja Calabrese • basil • toasted garlic",
                raw_price_text="19",
                price=19,
                canonical_category="seafood",
                protein=["mussels"],
                ingredients=["mussels", "nduja", "basil", "garlic"],
            ),
            item(
                "North End Cioppino",
                section="Mains",
                raw_description="Spicy brodo • grilled local fish • shellfish saffron rice (available with Maine lobster)",
                raw_price_text="38",
                price=38,
                canonical_category="seafood",
                canonical_dish="CIOPPINO",
                protein=["fish", "shellfish", "lobster"],
                ingredients=["fish", "shellfish", "saffron rice", "brodo"],
            ),
            item(
                "Georges Bank Sea Scallops",
                section="Mains",
                raw_description="Smoked bacon • Macomber turnip puree • wild mushrooms • Ward's Berry farm Swiss chard • lobster roe butter",
                raw_price_text="41",
                price=41,
                canonical_category="seafood",
                protein=["scallop"],
                ingredients=["sea scallops", "bacon", "turnip", "mushrooms", "lobster roe"],
            ),
            item(
                "Maine Lobster Roll",
                section="Sandwiches",
                raw_description="Available hot with butter or cold with mayo (available with caviar). Served on toasted Iggy's brioche roll with sea salt fries.",
                raw_price_text="MKT",
                market_price=True,
                canonical_category="seafood",
                canonical_dish="LOBSTER_ROLL",
                protein=["lobster"],
                ingredients=["lobster", "brioche"],
            ),
            item(
                "New England style 'fritto misto'",
                section="Sandwiches",
                raw_description="Pt. Judith calamari • Ipswich clams • Maine Lobster • cherry red hots • sweet reaper aioli",
                raw_price_text="31",
                price=31,
                canonical_category="seafood",
                canonical_dish="CALAMARI",
                protein=["calamari", "clams", "lobster"],
                preparation="fried",
                ingredients=["calamari", "ipswich clams", "lobster"],
            ),
            item(
                "Lobster spaghettini",
                section="Specials",
                raw_description="Monday special. Thin noodles in garlic, white wine, and tomato sauce with Maine lobster meat, breadcrumbs, and Parmesan.",
                canonical_category="pasta",
                canonical_dish="SEAFOOD_PASTA",
                protein=["lobster"],
                pasta_type="spaghettini",
                sauce="tomato white wine garlic",
                ingredients=["lobster", "garlic", "white wine", "tomato", "parmesan"],
                seasonal=True,
                confidence=0.8,
            ),
            item(
                "East coast oysters",
                section="Raw Bar",
                raw_description="East coast—MKT",
                raw_price_text="MKT",
                market_price=True,
                canonical_category="seafood",
                canonical_dish="OYSTERS",
                protein=["oyster"],
                preparation="raw",
            ),
        ],
    },
    {
        "restaurant_id": "NE_0003",
        "name": "Pizzeria Regina",
        "slug": "pizzeria-regina",
        "address": "11 1/2 Thacher Street, Boston, MA 02113",
        "latitude": 42.36535,
        "longitude": -71.05695,
        "establishment_type": "pizzeria",
        "primary_cuisine": "pizza",
        "secondary_cuisines": "italian",
        "official_website": "https://pizzeriaregina.com/north_end.html",
        "official_menu_url": "https://pizzeriaregina.com/assets/files/reg-quickserve-menu-426.pdf",
        "photo_url": "/restaurant-photos/pizzeria-regina.jpg",
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://pizzeriaregina.com/assets/files/reg-quickserve-menu-426.pdf",
                "source_format": "pdf",
            }
        ],
        "extractor_model": "manual_seed_v1",
        "items": [
            item(
                "Original 16\"",
                section="Pizza",
                raw_description="The North End tradition. Secret 100-year-old dough, spicy-sweet sauce, mozzarella.",
                raw_price_text="17.50",
                price=17.5,
                canonical_category="pizza",
                canonical_dish="CHEESE_PIZZA",
                size="16 inch",
                ingredients=["tomato sauce", "mozzarella"],
                dietary_tags=["vegetarian"],
                confidence=0.95,
            ),
            item(
                "Margherita (Fresh Basil)",
                section="Regina's Specialty Pizza",
                raw_description="Original Regina Pizza Sauce, fresh chopped basil with Mozzarella and Pecorino Romano.",
                canonical_category="pizza",
                canonical_dish="MARGHERITA",
                ingredients=["tomato sauce", "basil", "mozzarella", "pecorino romano"],
                dietary_tags=["vegetarian"],
                confidence=0.95,
            ),
            item(
                "Vegetarian Primavera (White Pizza)",
                section="Regina's Specialty Pizza",
                raw_description="Mozzarella, mushrooms, peppers, onions, black olives, fresh basil, marinated tomatoes and artichoke hearts with our garlic sauce.",
                canonical_category="pizza",
                canonical_dish="WHITE_PIZZA",
                sauce="garlic",
                ingredients=["mozzarella", "mushrooms", "peppers", "onions", "black olives", "basil", "tomato", "artichoke"],
                dietary_tags=["vegetarian"],
                confidence=0.94,
            ),
            item(
                "Quattro Formaggio (White Pizza)",
                section="Regina's Specialty Pizza",
                raw_description="Mozzarella, Ricotta, Pecorino Romano and Parmesan sprinkled with fresh basil and Regina's garlic sauce.",
                canonical_category="pizza",
                canonical_dish="WHITE_PIZZA",
                sauce="garlic",
                ingredients=["mozzarella", "ricotta", "pecorino romano", "parmesan", "basil"],
                dietary_tags=["vegetarian"],
                confidence=0.94,
            ),
            item(
                "Pepperoni",
                section="Traditional Toppings",
                raw_description="Traditional topping on original Regina pizza.",
                canonical_category="pizza",
                protein=["pork"],
                ingredients=["pepperoni"],
                confidence=0.8,
            ),
            item(
                "Regina's Sausage",
                section="Traditional Toppings",
                raw_description="Traditional topping.",
                canonical_category="pizza",
                protein=["pork"],
                ingredients=["sausage"],
                confidence=0.8,
            ),
        ],
    },
    {
        "restaurant_id": "NE_0004",
        "name": "Modern Pastry",
        "slug": "modern-pastry",
        "address": "257 Hanover Street, Boston, MA 02113",
        "latitude": 42.36355,
        "longitude": -71.05445,
        "establishment_type": "bakery",
        "primary_cuisine": "bakery",
        "secondary_cuisines": "dessert,cafe",
        "official_website": "https://modernpastry.com/",
        "official_menu_url": "https://modernpastry.com/pages/pastry-list",
        "photo_url": "/restaurant-photos/modern-pastry.jpg",
        "sources": [
            {
                "menu_type": "bakery",
                "source_url": "https://modernpastry.com/pages/pastry-list",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v1",
        "items": [
            item("Cannoli", section="Pastries", raw_description="Made fresh to order. Shells: plain, chocolate dipped, chocolate covered, mini. Fillings: traditional ricotta, vanilla custard, chocolate custard, whipped cream, chantilly cream.", canonical_category="dessert", canonical_dish="CANNOLI", ingredients=["ricotta"], dietary_tags=["vegetarian"], confidence=0.97),
            item("Lobster Tail", section="Pastries", canonical_category="dessert", canonical_dish="LOBSTER_TAIL_PASTRY", dietary_tags=["vegetarian"], confidence=0.97),
            item("Sfogliatella", section="Pastries", canonical_category="dessert", canonical_dish="SFOGLIATELLE", dietary_tags=["vegetarian"], confidence=0.97),
            item("Tiramisu", section="Pastries", canonical_category="dessert", canonical_dish="TIRAMISU", dietary_tags=["vegetarian"], confidence=0.97),
            item("Ricotta Pie Slice", section="Pastries", canonical_category="dessert", canonical_dish="RICOTTA_PIE", dietary_tags=["vegetarian"], confidence=0.97),
            item("Bomba", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Napoleon", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Rum Baba", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Limoncello", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.88),
            item("Cannoli with Ricotta Filling (GF ONLY)", section="Gluten-Free & Dairy-Free", canonical_category="dessert", canonical_dish="CANNOLI", ingredients=["ricotta"], dietary_tags=["gluten-free", "vegetarian"], confidence=0.95),
            item("Amaretti (Italian almond macaroons)", section="Cookies", canonical_category="dessert", ingredients=["almond"], dietary_tags=["vegetarian"], confidence=0.9),
            item("Almond Biscotti", section="Cookies", canonical_category="dessert", ingredients=["almond"], dietary_tags=["vegetarian"], confidence=0.9),
        ],
    },
    {
        "restaurant_id": "NE_0005",
        "name": "Bricco",
        "slug": "bricco",
        "address": "241 Hanover Street, Boston, MA 02113",
        "latitude": 42.36332,
        "longitude": -71.05462,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "seafood,steak",
        "official_website": "https://bricco.com/",
        "official_menu_url": "https://bricco.com/menu/",
        "photo_url": "/restaurant-photos/bricco.jpg",
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://bricco.com/menu/briccos-artisanal-pasta/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v1",
        "items": [
            item("Spinach Fettuccine", section="Artisanal Pasta", raw_description="Truffle besciamella, shaved black truffles", raw_price_text="$32", price=32, canonical_category="pasta", pasta_type="fettuccine", sauce="truffle bechamel", ingredients=["spinach", "truffle", "besciamella"], dietary_tags=["vegetarian"]),
            item("Spaghettoni al Pomodoro", section="Artisanal Pasta", raw_description="San Marzano tomatoes, fresh basil, shaved parmigiana", raw_price_text="$29", price=29, canonical_category="pasta", canonical_dish="POMODORO", pasta_type="spaghettoni", sauce="pomodoro", ingredients=["san marzano tomato", "basil", "parmigiano"], dietary_tags=["vegetarian"]),
            item("Garganelli Amatriciana", section="Artisanal Pasta", raw_description="Niman Ranch pancetta, spicy Colino tomato, pecorino romano", raw_price_text="$29", price=29, canonical_category="pasta", canonical_dish="AMATRICIANA", pasta_type="garganelli", sauce="amatriciana", protein=["pork"], ingredients=["pancetta", "tomato", "pecorino romano"]),
            item("Farfalle Tartufate", section="Artisanal Pasta", raw_description="Lobster meat, fava beans, pancetta, black truffle, lobster fumét", raw_price_text="$34", price=34, canonical_category="pasta", canonical_dish="SEAFOOD_PASTA", pasta_type="farfalle", protein=["lobster", "pork"], ingredients=["lobster", "fava beans", "pancetta", "black truffle", "lobster fumet"]),
            item("Chittarrine Jumbo Shrimp", section="Artisanal Pasta", raw_description="Zucchini, limoncello, peperoncino", raw_price_text="$34", price=34, canonical_category="pasta", canonical_dish="SEAFOOD_PASTA", pasta_type="chitarrine", protein=["shrimp"], ingredients=["shrimp", "zucchini", "limoncello", "peperoncino"]),
            item("Tortelli Pumpkin", section="Artisanal Pasta", raw_description="Amaretti & honey, sage butter, root vegetables, ricotta salata", raw_price_text="$31", price=31, canonical_category="pasta", canonical_dish="SQUASH_RAVIOLI", pasta_type="tortelli", sauce="sage butter", ingredients=["pumpkin", "amaretti", "honey", "sage", "ricotta salata"], dietary_tags=["vegetarian"]),
            item("Pappardelle al Cinghiale", section="Artisanal Pasta", raw_description="Wild boar braised in red wine with porcini mushrooms", raw_price_text="$34", price=34, canonical_category="pasta", pasta_type="pappardelle", protein=["boar"], ingredients=["wild boar", "red wine", "porcini"]),
            item("Gnocchetti Sorrentina", section="Artisanal Pasta", raw_description="Baked with bufala mozzarella, tomatoes, basil", raw_price_text="$29", price=29, canonical_category="pasta", pasta_type="gnocchi", ingredients=["bufala mozzarella", "tomato", "basil"], dietary_tags=["vegetarian"]),
            item("Risotto", section="Artisanal Pasta", raw_description="Chef's daily special", raw_price_text="MKT", market_price=True, canonical_category="pasta", pasta_type="risotto"),
            item("Octopus", section="Signature Appetizers", raw_description="Dry roasted with ginger & jalapeño crust with purple potato and string bean salad", raw_price_text="$24", price=24, canonical_category="seafood", canonical_dish="OCTOPUS", protein=["octopus"], preparation="roasted", ingredients=["octopus", "ginger", "jalapeño", "potato"]),
            item("Arancini", section="Signature Appetizers", raw_description="Sausage & broccolini, green arrabiata, parmesan aioli", raw_price_text="$22", price=22, canonical_category="antipasti", canonical_dish="ARANCINI", protein=["pork"], ingredients=["sausage", "broccolini", "arrabiata"]),
            item("Meatballs", section="Signature Appetizers", raw_description="CAB Prime, served with fresh ricotta & crostini", raw_price_text="$21", price=21, canonical_category="italian_american", canonical_dish="MEATBALLS", protein=["beef"], ingredients=["beef", "ricotta"]),
            item("Frittura Mista", section="Signature Appetizers", raw_description="Calamari, scallops, shrimp, fried onion strings & tartar dip", raw_price_text="$24", price=24, canonical_category="seafood", canonical_dish="CALAMARI", protein=["calamari", "scallop", "shrimp"], preparation="fried"),
            item("Zucchini Flowers", section="Signature Appetizers", raw_description="Stuffed with truffle ricotta cheese, tempura, grilled vegetables", raw_price_text="$21", price=21, canonical_category="antipasti", ingredients=["zucchini flower", "truffle ricotta"], dietary_tags=["vegetarian"]),
            item("Bricco's Brodetto", section="From the Sea", raw_description="Half lobster, shrimp, swordfish, monkfish, calamari, Wellfleet clams and mussels, Colino tomatoes, fish fumet, grilled asparagus, bruschette", raw_price_text="$59", price=59, canonical_category="seafood", canonical_dish="CIOPPINO", protein=["lobster", "shrimp", "swordfish", "monkfish", "calamari", "clams", "mussels"]),
            item("Mediterranean Branzino", section="From the Sea", raw_description="Roasted herb potatoes, baby spinach, pinzimonio sauce", raw_price_text="$49", price=49, canonical_category="seafood", protein=["branzino"], ingredients=["branzino", "potato", "spinach"]),
            item("Drinkthat Espresso Martini Tiramisú", section="I Dolci", raw_description="Lady fingers soaked in espresso martini and mascarpone cream", raw_price_text="$19", price=19, canonical_category="dessert", canonical_dish="TIRAMISU", ingredients=["ladyfingers", "espresso martini", "mascarpone"], dietary_tags=["vegetarian"]),
            item("Homemade Gelato Trio", section="I Dolci", raw_description="Trio of flavors: chocolate, vanilla, hazelnut", raw_price_text="$14", price=14, canonical_category="dessert", ingredients=["gelato"], dietary_tags=["vegetarian"]),
        ],
    },
]
