"""Hand-seeded North End corpus for Sprint 0.

Raw names/descriptions/prices come from official restaurant pages, refreshed
2026-08-24 against a full audit of each live site (see git history for the
per-restaurant audit that drove this pass). Giacomo's official menu is
JavaScript-rendered — a plain HTTP fetch (the same method
scripts/ingest_menu.py uses) only sees a title shell, so this data was
captured via a rendered browser session rather than a raw fetch; re-running
ingest_menu.py against giacomosboston.com/menu will NOT reproduce it without
a headless-browser fetch path, which doesn't exist yet.

Deliberately excluded from all restaurants: beverages (beer/wine/cocktails/
coffee) and per-topping add-ons — this schema models dishes, not drinks or
modifiers.

Bricco's menu spans 7 separate official pages (salads, appetizers, pasta,
sea, land, beef & chops, dolci); menu_sources is restaurant-granularity, not
item-granularity, so `source_url` records the menu landing page that links
all of them rather than each item's exact sub-page. A future schema
enhancement could track per-item source URLs if that granularity matters.

Missing prices are left null — never invented.
"""

from __future__ import annotations

from typing import Any

CANONICAL_DISHES: list[dict[str, Any]] = [
    {
        "canonical_dish_id": "LOBSTER_RAVIOLI",
        "canonical_name": "Lobster ravioli",
        "category": "pasta",
        "subcategory": "stuffed",
        "description": "Ravioli filled with lobster.",
        "aliases": ["lobster ravioli", "ravioli di astice"],
    },
    {
        "canonical_dish_id": "SQUASH_RAVIOLI",
        "canonical_name": "Butternut squash ravioli",
        "category": "pasta",
        "subcategory": "stuffed",
        "description": "Ravioli filled with squash or pumpkin.",
        "aliases": ["butternut squash ravioli", "pumpkin ravioli", "pumpkin tortellini", "tortelli pumpkin"],
    },
    {
        "canonical_dish_id": "CHICKEN_PARMIGIANA",
        "canonical_name": "Chicken parmigiana",
        "category": "italian_american",
        "subcategory": "parm",
        "description": "Breaded chicken with tomato and mozzarella.",
        "aliases": ["chicken parm", "chicken parmesan", "pollo parmigiana"],
    },
    {
        "canonical_dish_id": "VEAL_PARMIGIANA",
        "canonical_name": "Veal parmigiana",
        "category": "italian_american",
        "subcategory": "parm",
        "description": "Breaded veal with tomato and mozzarella.",
        "aliases": ["veal parm", "vitello parmigiana"],
    },
    {
        "canonical_dish_id": "EGGPLANT_PARMIGIANA",
        "canonical_name": "Eggplant parmigiana",
        "category": "italian_american",
        "subcategory": "parm",
        "description": "Layered eggplant with tomato and cheese.",
        "aliases": ["eggplant parm", "eggplant rollatini", "melanzane"],
    },
    {
        "canonical_dish_id": "CHICKEN_MARSALA",
        "canonical_name": "Chicken marsala",
        "category": "italian_american",
        "subcategory": "marsala",
        "description": "Sauteed chicken, mushrooms, and Marsala wine sauce.",
        "aliases": ["pollo marsala"],
    },
    {
        "canonical_dish_id": "VEAL_MARSALA",
        "canonical_name": "Veal marsala",
        "category": "italian_american",
        "subcategory": "marsala",
        "description": "Sauteed veal, mushrooms, and Marsala wine sauce.",
        "aliases": ["vitello marsala"],
    },
    {
        "canonical_dish_id": "MEATBALLS",
        "canonical_name": "Meatballs",
        "category": "italian_american",
        "subcategory": "meat",
        "description": "Beef or mixed meatballs, typically with ricotta or marinara.",
        "aliases": ["polpette", "homemade meatballs"],
    },
    {
        "canonical_dish_id": "FRUTTI_DI_MARE",
        "canonical_name": "Frutti di mare",
        "category": "pasta",
        "subcategory": "seafood",
        "description": "Mixed seafood pasta.",
        "aliases": ["frutti di mare linguine", "seafood linguine", "zuppa di pesce"],
    },
    {
        "canonical_dish_id": "SEAFOOD_PASTA",
        "canonical_name": "Seafood pasta",
        "category": "pasta",
        "subcategory": "seafood",
        "description": "Pasta with one or more seafood proteins.",
        "aliases": ["shrimp linguine", "scallops linguine", "mussels linguine", "lobster pasta"],
    },
    {
        "canonical_dish_id": "AMATRICIANA",
        "canonical_name": "Amatriciana",
        "category": "pasta",
        "subcategory": "sauce",
        "description": "Tomato, guanciale or pancetta, pecorino.",
        "aliases": ["garganelli amatriciana"],
    },
    {
        "canonical_dish_id": "POMODORO",
        "canonical_name": "Pomodoro",
        "category": "pasta",
        "subcategory": "sauce",
        "description": "Tomato and basil pasta.",
        "aliases": ["al pomodoro", "spaghettoni al pomodoro"],
    },
    {
        "canonical_dish_id": "MARGHERITA",
        "canonical_name": "Margherita pizza",
        "category": "pizza",
        "subcategory": "classic",
        "description": "Tomato, mozzarella, basil.",
        "aliases": ["pizza margherita"],
    },
    {
        "canonical_dish_id": "CHEESE_PIZZA",
        "canonical_name": "Cheese pizza",
        "category": "pizza",
        "subcategory": "classic",
        "description": "Plain cheese / original pie.",
        "aliases": ["original pizza", "cheese pie"],
    },
    {
        "canonical_dish_id": "WHITE_PIZZA",
        "canonical_name": "White pizza",
        "category": "pizza",
        "subcategory": "white",
        "description": "Pizza without red sauce.",
        "aliases": ["quattro formaggio", "vegetarian primavera"],
    },
    {
        "canonical_dish_id": "CANNOLI",
        "canonical_name": "Cannoli",
        "category": "dessert",
        "subcategory": "pastry",
        "description": "Fried pastry shell with sweet ricotta or custard.",
        "aliases": ["cannoli siciliani"],
    },
    {
        "canonical_dish_id": "TIRAMISU",
        "canonical_name": "Tiramisu",
        "category": "dessert",
        "subcategory": "cake",
        "description": "Espresso-soaked ladyfingers and mascarpone.",
        "aliases": ["tiramisú"],
    },
    {
        "canonical_dish_id": "LOBSTER_TAIL_PASTRY",
        "canonical_name": "Lobster tail pastry",
        "category": "dessert",
        "subcategory": "pastry",
        "description": "Sfogliatella-style shell filled with cream; not seafood.",
        "aliases": ["lobster tail", "code d'aragosta"],
    },
    {
        "canonical_dish_id": "SFOGLIATELLE",
        "canonical_name": "Sfogliatelle",
        "category": "dessert",
        "subcategory": "pastry",
        "description": "Layered shell pastry, typically ricotta.",
        "aliases": ["sfogliatella"],
    },
    {
        "canonical_dish_id": "RICOTTA_PIE",
        "canonical_name": "Ricotta pie",
        "category": "dessert",
        "subcategory": "pie",
        "description": "Italian ricotta pie.",
        "aliases": ["pizza di ricotta", "ricotta pie slice"],
    },
    {
        "canonical_dish_id": "OCTOPUS",
        "canonical_name": "Octopus",
        "category": "seafood",
        "subcategory": "cephalopod",
        "description": "Octopus, grilled or roasted.",
        "aliases": ["spanish octopus", "polpo"],
    },
    {
        "canonical_dish_id": "CALAMARI",
        "canonical_name": "Calamari",
        "category": "seafood",
        "subcategory": "cephalopod",
        "description": "Fried or sautéed squid.",
        "aliases": ["fried calamari", "calamari fritti"],
    },
    {
        "canonical_dish_id": "CIOPPINO",
        "canonical_name": "Cioppino",
        "category": "seafood",
        "subcategory": "stew",
        "description": "Seafood stew in tomato/brodo.",
        "aliases": ["north end cioppino", "brodetto"],
    },
    {
        "canonical_dish_id": "LOBSTER_ROLL",
        "canonical_name": "Lobster roll",
        "category": "seafood",
        "subcategory": "sandwich",
        "description": "Lobster meat on a bun, hot butter or cold mayo.",
        "aliases": ["maine lobster roll"],
    },
    {
        "canonical_dish_id": "OYSTERS",
        "canonical_name": "Oysters",
        "category": "seafood",
        "subcategory": "raw_bar",
        "description": "Oysters on the half shell.",
        "aliases": ["east coast oysters", "west coast oysters", "half dozen oysters"],
    },
    {
        "canonical_dish_id": "ARANCINI",
        "canonical_name": "Arancini",
        "category": "antipasti",
        "subcategory": "fried",
        "description": "Fried risotto balls.",
        "aliases": ["rice balls"],
    },
    {
        "canonical_dish_id": "BURRATA",
        "canonical_name": "Burrata",
        "category": "antipasti",
        "subcategory": "cheese",
        "description": "Fresh burrata.",
        "aliases": ["burrata caprese"],
    },
    {
        "canonical_dish_id": "CAPRESE",
        "canonical_name": "Caprese salad",
        "category": "antipasti",
        "subcategory": "salad",
        "description": "Tomato, fresh mozzarella, basil.",
        "aliases": ["caprese salad", "insalata caprese", "mozzarella di bufala caprese"],
    },
    {
        "canonical_dish_id": "CARBONARA",
        "canonical_name": "Carbonara",
        "category": "pasta",
        "subcategory": "sauce",
        "description": "Egg, pecorino, guanciale, pepper.",
        "aliases": ["spaghetti carbonara"],
    },
]


def item(
    raw_name: str,
    *,
    section: str,
    raw_description: str | None = None,
    raw_price_text: str | None = None,
    price: float | None = None,
    canonical_category: str | None = None,
    canonical_dish: str | None = None,
    protein: list[str] | None = None,
    pasta_type: str | None = None,
    sauce: str | None = None,
    preparation: str | None = None,
    ingredients: list[str] | None = None,
    dietary_tags: list[str] | None = None,
    portion: str | None = None,
    size: str | None = None,
    seasonal: bool = False,
    market_price: bool = False,
    confidence: float = 0.92,
) -> dict[str, Any]:
    return {
        "raw_name": raw_name,
        "raw_description": raw_description,
        "raw_price_text": raw_price_text,
        "price": price,
        "menu_section": section,
        "canonical_category": canonical_category,
        "canonical_dish": canonical_dish,
        "protein": protein,
        "pasta_type": pasta_type,
        "sauce": sauce,
        "preparation": preparation,
        "ingredients": ingredients,
        "dietary_tags": dietary_tags,
        "portion": portion,
        "size": size,
        "seasonal": seasonal,
        "market_price": market_price,
        "available": True,
        "normalization_confidence": confidence,
    }


RESTAURANTS: list[dict[str, Any]] = [
    {
        "restaurant_id": "NE_0001",
        "name": "Giacomo's Ristorante",
        "slug": "giacomos-ristorante",
        "address": "355 Hanover Street, Boston, MA 02113",
        "latitude": 42.364591,
        "longitude": -71.053375,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "seafood",
        "official_website": "https://giacomosboston.com/",
        "official_menu_url": "https://giacomosboston.com/menu",
        "photo_url": "/restaurant-photos/giacomos-ristorante.jpg",
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://giacomosboston.com/menu",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v2_browser_rendered",
        "items": [
            # Antipasti
            item("Fried Calamari", section="Antipasti", raw_price_text="$17", price=17, canonical_category="seafood", canonical_dish="CALAMARI", protein=["calamari"], preparation="fried", confidence=0.96),
            item("Garlic Bread", section="Antipasti", raw_price_text="$10", price=10, canonical_category="antipasti", dietary_tags=["vegetarian"], ingredients=["bread", "garlic"], confidence=0.96),
            item("Broccoli, Sautéed", section="Antipasti", raw_description="In garlic and oil.", raw_price_text="$11", price=11, canonical_category="antipasti", dietary_tags=["vegetarian"], ingredients=["broccoli", "garlic", "oil"], confidence=0.96),
            item("Antipasto", section="Antipasti", raw_description="Imported cheese, soppressata, and roasted red peppers.", raw_price_text="$20", price=20, canonical_category="antipasti", protein=["pork"], ingredients=["cheese", "soppressata", "roasted red peppers"], confidence=0.96),
            item("Mussels", section="Antipasti", raw_description="Your choice of sauce.", raw_price_text="$16", price=16, canonical_category="seafood", protein=["mussels"], confidence=0.96),
            item("Meatballs", section="Antipasti", raw_description="With tomato sauce.", raw_price_text="$14", price=14, canonical_category="italian_american", canonical_dish="MEATBALLS", protein=["beef"], sauce="tomato", confidence=0.96),
            item("Caprese Salad", section="Antipasti", raw_description="Tomato, fresh mozzarella, basil, extra virgin olive oil, balsamic drizzle.", raw_price_text="$14", price=14, canonical_category="antipasti", canonical_dish="CAPRESE", dietary_tags=["vegetarian"], ingredients=["tomato", "mozzarella", "basil"], confidence=0.96),
            item("Eggplant Rollatini", section="Antipasti", raw_description="Rolled and stuffed with ricotta, romano and mozzarella cheese in a tomato sauce.", raw_price_text="$12", price=12, canonical_category="italian_american", canonical_dish="EGGPLANT_PARMIGIANA", dietary_tags=["vegetarian"], ingredients=["eggplant", "ricotta", "romano", "mozzarella", "tomato sauce"], confidence=0.96),
            item("House Salad", section="Antipasti", raw_description="With a balsamic vinaigrette.", raw_price_text="$12", price=12, canonical_category="salad", dietary_tags=["vegetarian"], confidence=0.96),
            item("Bruschetta", section="Antipasti", raw_description="With fresh tomatoes on toasted ciabatta bread.", raw_price_text="$12", price=12, canonical_category="antipasti", dietary_tags=["vegetarian"], ingredients=["tomato", "ciabatta"], confidence=0.96),
            item("Caesar Salad", section="Antipasti", raw_description="For one / for two.", raw_price_text="$12 / $18", price=12, canonical_category="salad", portion="for one; $18 for two", confidence=0.94),
            item("Burrata", section="Antipasti", raw_description="Filled ball over diced tomatoes with basil and balsamic vinegar.", raw_price_text="$16", price=16, canonical_category="antipasti", canonical_dish="BURRATA", dietary_tags=["vegetarian"], ingredients=["burrata", "tomato", "basil"], confidence=0.96),
            item("Fried Mozzarella Marinara", section="Antipasti", raw_price_text="$14", price=14, canonical_category="antipasti", dietary_tags=["vegetarian"], preparation="fried", ingredients=["mozzarella", "marinara"], confidence=0.96),
            # Grilled Seafood
            item("Swordfish Steak", section="Grilled Seafood", raw_description="Served with fresh grilled vegetables and a side of pasta marinara.", raw_price_text="$29", price=29, canonical_category="seafood", protein=["swordfish"], preparation="grilled", confidence=0.96),
            item("Salmon Fillet", section="Grilled Seafood", raw_description="Served with fresh grilled vegetables and a side of pasta marinara.", raw_price_text="$29", price=29, canonical_category="seafood", protein=["salmon"], preparation="grilled", confidence=0.96),
            item("Tuna Steak", section="Grilled Seafood", raw_description="Served with fresh grilled vegetables and a side of pasta marinara.", raw_price_text="$29", price=29, canonical_category="seafood", protein=["tuna"], preparation="grilled", confidence=0.96),
            # Marsalas & Parmigianas
            item("Veal Marsala", section="Marsalas & Parmigianas", raw_description="Veal sauteed with mushrooms and prosciutto in a Marsala wine sauce; side of pasta marinara.", raw_price_text="$26", price=26, canonical_category="italian_american", canonical_dish="VEAL_MARSALA", protein=["veal", "pork"], sauce="marsala", ingredients=["veal", "mushroom", "prosciutto", "marsala wine"], confidence=0.96),
            item("Chicken Marsala", section="Marsalas & Parmigianas", raw_description="Chicken sauteed with mushrooms and prosciutto in a Marsala wine sauce; side of pasta marinara.", raw_price_text="$24", price=24, canonical_category="italian_american", canonical_dish="CHICKEN_MARSALA", protein=["chicken", "pork"], sauce="marsala", confidence=0.96),
            item("Veal Parmigiana", section="Marsalas & Parmigianas", raw_description="Breaded veal, mozzarella, marinara sauce; side of pasta marinara.", raw_price_text="$26", price=26, canonical_category="italian_american", canonical_dish="VEAL_PARMIGIANA", protein=["veal"], sauce="marinara", confidence=0.96),
            item("Chicken Parmigiana", section="Marsalas & Parmigianas", raw_description="Breaded chicken, mozzarella, marinara sauce; side of pasta marinara.", raw_price_text="$24", price=24, canonical_category="italian_american", canonical_dish="CHICKEN_PARMIGIANA", protein=["chicken"], sauce="marinara", confidence=0.96),
            # Vegetariano
            item("Eggplant Parmigiana", section="Vegetariano", raw_description="With a side of pasta in a marinara sauce.", raw_price_text="$22", price=22, canonical_category="italian_american", canonical_dish="EGGPLANT_PARMIGIANA", dietary_tags=["vegetarian"], sauce="marinara", confidence=0.96),
            item("Fusilli Siciliana", section="Vegetariano", raw_description="Eggplant, onions, mozzarella in a plum tomato sauce.", raw_price_text="$22", price=22, canonical_category="pasta", pasta_type="fusilli", dietary_tags=["vegetarian"], ingredients=["eggplant", "onion", "mozzarella", "tomato"], confidence=0.96),
            item("Pumpkin Tortellini", section="Vegetariano", raw_description="In a fresh sage, mascarpone cheese sauce.", raw_price_text="$22", price=22, canonical_category="pasta", canonical_dish="SQUASH_RAVIOLI", pasta_type="tortellini", sauce="sage mascarpone", dietary_tags=["vegetarian"], confidence=0.96),
            # House Special
            item("Zuppa di Pesce", section="House Special", raw_description="Dinner for two: lobster, shrimp, scallops, calamari, clams and mussels over linguine, choice of sauce. $132 with a bottle of house Chianti or Pinot Grigio; +$10 per extra person.", raw_price_text="$98", price=98, canonical_category="pasta", canonical_dish="FRUTTI_DI_MARE", protein=["lobster", "shrimp", "scallop", "calamari", "clams", "mussels"], pasta_type="linguine", ingredients=["lobster", "shrimp", "scallops", "calamari", "clams", "mussels"], portion="dinner for two, +$10/extra person", confidence=0.97),
            # Linguine — all "choice of sauce: pesto, red, fra diavolo, scampi, Giacomo, or fracomo"
            item("Linguine with Mussels or Calamari", section="Linguine", raw_description="Choice of sauce: pesto, red, fra diavolo, scampi, Giacomo, or fracomo.", raw_price_text="$24", price=24, canonical_category="pasta", pasta_type="linguine", protein=["mussels", "calamari"], confidence=0.94),
            item("Linguine with Scallops", section="Linguine", raw_description="Choice of sauce: pesto, red, fra diavolo, scampi, Giacomo, or fracomo.", raw_price_text="$29", price=29, canonical_category="pasta", pasta_type="linguine", protein=["scallop"], confidence=0.94),
            item("Linguine with Mussels and Calamari", section="Linguine", raw_description="Choice of sauce: pesto, red, fra diavolo, scampi, Giacomo, or fracomo.", raw_price_text="$24", price=24, canonical_category="pasta", pasta_type="linguine", protein=["mussels", "calamari"], confidence=0.94),
            item("Linguine with Shrimp", section="Linguine", raw_description="Choice of sauce: pesto, red, fra diavolo, scampi, Giacomo, or fracomo.", raw_price_text="$26", price=26, canonical_category="pasta", pasta_type="linguine", protein=["shrimp"], confidence=0.94),
            item("Linguine with Clams", section="Linguine", raw_description="Choice of sauce: pesto, red, fra diavolo, scampi, Giacomo, or fracomo.", raw_price_text="$26", price=26, canonical_category="pasta", pasta_type="linguine", protein=["clams"], confidence=0.94),
            item("Linguine with Shrimp and Scallops", section="Linguine", raw_description="Choice of sauce: pesto, red, fra diavolo, scampi, Giacomo, or fracomo.", raw_price_text="$29", price=29, canonical_category="pasta", pasta_type="linguine", protein=["shrimp", "scallop"], confidence=0.94),
            item("Linguine with Mussels and Clams", section="Linguine", raw_description="Choice of sauce: pesto, red, fra diavolo, scampi, Giacomo, or fracomo.", raw_price_text="$28", price=28, canonical_category="pasta", pasta_type="linguine", protein=["mussels", "clams"], confidence=0.94),
            item("Frutti Di Mare Linguine", section="Linguine", raw_description="Shrimp, scallops, calamari, clams, and mussels. Choice of pesto, red, fra diavolo, giacomo, fracomo, or scampi.", raw_price_text="$38", price=38, canonical_category="pasta", canonical_dish="FRUTTI_DI_MARE", protein=["shrimp", "scallop", "calamari", "clams", "mussels"], pasta_type="linguine", ingredients=["shrimp", "scallops", "calamari", "clams", "mussels"], confidence=0.96),
            # Fettuccini
            item("Fettuccini with Swordfish & Tuna", section="Fettuccini", raw_description="Pieces in a pesto cream sauce.", raw_price_text="$29", price=29, canonical_category="pasta", pasta_type="fettuccine", sauce="pesto cream", protein=["swordfish", "tuna"], confidence=0.95),
            item("Fettuccini with Salmon & Sundried Tomatoes", section="Fettuccini", raw_description="In a lobster-based tomato cream sauce.", raw_price_text="$28", price=28, canonical_category="pasta", pasta_type="fettuccine", sauce="lobster tomato cream", protein=["salmon"], ingredients=["salmon", "sundried tomato"], confidence=0.95),
            item("Fettuccini with Chicken, Peppers and Onions", section="Fettuccini", raw_description="In a tomato cream sauce.", raw_price_text="$24", price=24, canonical_category="pasta", pasta_type="fettuccine", sauce="tomato cream", protein=["chicken"], confidence=0.95),
            item("Fettuccini with Prosciutto and Peas", section="Fettuccini", raw_description="In a garlic cream sauce.", raw_price_text="$22", price=22, canonical_category="pasta", pasta_type="fettuccine", sauce="garlic cream", protein=["pork"], confidence=0.95),
            # Ziti
            item("Ziti with Shrimp, Scallops and Broccoli", section="Ziti", raw_description="In a garlic cream sauce.", raw_price_text="$29", price=29, canonical_category="pasta", pasta_type="ziti", sauce="garlic cream", protein=["shrimp", "scallop"], confidence=0.95),
            item("Ziti with Chicken and Shrimp", section="Ziti", raw_description="In a pesto cream sauce.", raw_price_text="$26", price=26, canonical_category="pasta", pasta_type="ziti", sauce="pesto cream", protein=["chicken", "shrimp"], confidence=0.95),
            item("Ziti with Chicken and Broccoli", section="Ziti", raw_description="In a garlic cream sauce.", raw_price_text="$24", price=24, canonical_category="pasta", pasta_type="ziti", sauce="garlic cream", protein=["chicken"], confidence=0.95),
            # Ravioli
            item("Lobster Ravioli", section="Ravioli", raw_description="Served with diced tomato in a garlic cream sauce.", raw_price_text="$28", price=28, canonical_category="pasta", canonical_dish="LOBSTER_RAVIOLI", protein=["lobster"], pasta_type="ravioli", sauce="garlic cream", ingredients=["lobster", "tomato", "garlic", "cream"], confidence=0.96),
            item("Butternut Squash Ravioli", section="Ravioli", raw_description="Served with diced asparagus in a prosciutto, mascarpone cheese sauce.", raw_price_text="$24", price=24, canonical_category="pasta", canonical_dish="SQUASH_RAVIOLI", pasta_type="ravioli", protein=["pork"], ingredients=["butternut squash", "asparagus", "prosciutto", "mascarpone"], confidence=0.96),
        ],
    },
    {
        "restaurant_id": "NE_0002",
        "name": "Neptune Oyster",
        "slug": "neptune-oyster",
        "address": "63 Salem Street, Boston, MA 02113",
        "latitude": 42.36415,
        "longitude": -71.05585,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "seafood",
        "secondary_cuisines": None,
        "official_website": "https://neptuneoyster.com/",
        "official_menu_url": "https://www.neptuneoyster.com/menu",
        "photo_url": "/restaurant-photos/neptune-oyster.jpg",
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://www.neptuneoyster.com/menu",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v2",
        "items": [
            # Crudo
            item("Golden Sea Bream", section="Crudo", raw_description="Honeycrisp Apple • black lava sea salt", raw_price_text="18", price=18, canonical_category="seafood", protein=["bream"], preparation="crudo", ingredients=["sea bream", "honeycrisp apple", "black lava sea salt"], confidence=0.95),
            item("Bluefin", section="Crudo", raw_description="Piri Piri pepitas • Castelvetrano olive", raw_price_text="21", price=21, canonical_category="seafood", protein=["tuna"], preparation="crudo", ingredients=["bluefin tuna", "piri piri pepitas", "castelvetrano olive"], confidence=0.95),
            item("Bay Scallop", section="Crudo", raw_description="Nardello • cucumber • Duxbury sea salt", raw_price_text="MKT", market_price=True, canonical_category="seafood", protein=["scallop"], preparation="crudo", ingredients=["bay scallop", "nardello pepper", "cucumber"], confidence=0.95),
            # Classics
            item("Wellfleet Clam Chowder", section="Classics", raw_description="Salt pork • thyme", raw_price_text="15", price=15, canonical_category="seafood", protein=["clams"], ingredients=["clam", "salt pork", "thyme"], confidence=0.95),
            item("Spanish Octopus", section="Classics", raw_description="Marcona almond romesco • cauliflower • Espelette oil", raw_price_text="22", price=22, canonical_category="seafood", canonical_dish="OCTOPUS", protein=["octopus"], ingredients=["octopus", "marcona almond", "romesco", "cauliflower"], confidence=0.95),
            item("Fried Ipswich Clams", section="Classics", raw_description="House tartar • lemon", raw_price_text="MKT", market_price=True, canonical_category="seafood", protein=["clams"], preparation="fried", ingredients=["ipswich clams", "tartar", "lemon"], confidence=0.95),
            item("Neptune Johnnycake", section="Classics", raw_description="Honey butter • Boston smoked bluefish • sturgeon caviar", raw_price_text="21", price=21, canonical_category="seafood", protein=["bluefish"], ingredients=["johnnycake", "honey butter", "smoked bluefish", "sturgeon caviar"], confidence=0.95),
            item("Acadian Blue Mussels", section="Classics", raw_description="Nduja Calabrese • basil • toasted garlic", raw_price_text="19", price=19, canonical_category="seafood", protein=["mussels"], ingredients=["mussels", "nduja", "basil", "garlic"], confidence=0.95),
            item("Bluefin 'Coyne' Crostini", section="Classics", raw_description="Tuna Tartare, Iggy's baguette, bomba pistachio pesto", raw_price_text="23", price=23, canonical_category="seafood", protein=["tuna"], preparation="crudo", ingredients=["tuna", "baguette", "pistachio pesto"], confidence=0.93),
            item("Razor Clam Casino", section="Classics", raw_description="Smoked bacon, chili oil, parsley", raw_price_text="18", price=18, canonical_category="seafood", protein=["clams", "pork"], ingredients=["razor clam", "bacon", "chili oil"], confidence=0.93),
            item("Oyster 'Piggybacks'", section="Classics", raw_description="Berkshire pulled pork, blueberry cornbread, maple walnut butter", raw_price_text="17", price=17, canonical_category="seafood", canonical_dish="OYSTERS", protein=["oyster", "pork"], ingredients=["oyster", "pulled pork", "cornbread"], confidence=0.93),
            # Salads
            item("Whole Azorean Sardines", section="Salads", raw_description="Maplebrook Farms Burrata, toybox tomato, basil pesto", raw_price_text="24", price=24, canonical_category="seafood", protein=["sardine"], ingredients=["sardine", "burrata", "tomato", "basil pesto"], confidence=0.93),
            item("Maine Peekytoe Crab", section="Salads", raw_description="Verrill Farm's butter lettuce, avocado, roseheart radish, dulce, pickled beet root, almond vinaigrette", raw_price_text="31", price=31, canonical_category="seafood", protein=["crab"], ingredients=["crab", "butter lettuce", "avocado", "radish"], confidence=0.93),
            # Mains
            item("Georges Bank Sea Scallops", section="Mains", raw_description="Smoked bacon • Macomber turnip puree • wild mushrooms • Ward's Berry farm Swiss chard • lobster roe butter", raw_price_text="41", price=41, canonical_category="seafood", protein=["scallop"], ingredients=["sea scallops", "bacon", "turnip", "mushrooms", "lobster roe"], confidence=0.95),
            item("North End Cioppino", section="Mains", raw_description="Spicy brodo • grilled local fish • shellfish saffron rice (available with Maine lobster)", raw_price_text="38", price=38, canonical_category="seafood", canonical_dish="CIOPPINO", protein=["fish", "shellfish", "lobster"], ingredients=["fish", "shellfish", "saffron rice", "brodo"], confidence=0.95),
            item("Whole Rockport Mackerel", section="Mains", raw_description="Basque piperrada, garlic fingerlings, tximitxurri, fennel", raw_price_text="31", price=31, canonical_category="seafood", protein=["mackerel"], ingredients=["mackerel", "piperrada", "fingerling potato", "fennel"], confidence=0.93),
            item("MA Bay Bluefin Tuna", section="Mains", raw_description="Haricot verts, Nicoise olives, white anchovy, farm egg, Dijon vinaigrette", raw_price_text="42", price=42, canonical_category="seafood", protein=["tuna"], ingredients=["bluefin tuna", "haricot verts", "nicoise olives", "egg"], confidence=0.93),
            item("Acadian Redfish & Chips", section="Mains", raw_description="AVW malt vinegar aioli, pickles, parsley", raw_price_text="33", price=33, canonical_category="seafood", protein=["redfish"], preparation="fried", ingredients=["redfish", "malt vinegar aioli", "pickles"], confidence=0.93),
            item("Southcoast Black Sea Bass", section="Mains", raw_description="Littleneck clams, fava bean succotash, linguica, Atlantic kelp butter", raw_price_text="37", price=37, canonical_category="seafood", protein=["sea bass", "clams"], ingredients=["black sea bass", "littleneck clams", "fava bean", "linguica"], confidence=0.93),
            item("Royal Red Shrimp 'Mozambique'", section="Mains", raw_description="Camargue red rice, azafran, Brussels sprouts, pea shoots", raw_price_text="MKT", market_price=True, canonical_category="seafood", protein=["shrimp"], ingredients=["shrimp", "red rice", "brussels sprouts"], confidence=0.93),
            item("N.O.B. Clambake", section="Mains", raw_description="Whole 2lb Maine lobster, clams, chorizo, sweet corn", raw_price_text="MKT", market_price=True, canonical_category="seafood", protein=["lobster", "clams", "pork"], ingredients=["lobster", "clams", "chorizo", "corn"], confidence=0.93),
            item("16 oz Bone-in Ribeye", section="Mains", raw_description="House cut fries, mojo rojo, urchin butter", raw_price_text="79", price=79, canonical_category="steak", protein=["beef"], size="16 oz", ingredients=["ribeye", "fries", "urchin butter"], confidence=0.93),
            # Sandwiches
            item("Neptune Burger", section="Sandwiches", raw_description="Vermont cheddar, fried oysters, garlic mayo, relish, on toasted Iggy's brioche roll with sea salt fries", raw_price_text="25", price=25, canonical_category="seafood", protein=["beef", "oyster"], ingredients=["beef patty", "cheddar", "fried oysters", "brioche"], confidence=0.93),
            item("New England style 'fritto misto'", section="Sandwiches", raw_description="Pt. Judith calamari • Ipswich clams • Maine Lobster • cherry red hots • sweet reaper aioli", raw_price_text="31", price=31, canonical_category="seafood", canonical_dish="CALAMARI", protein=["calamari", "clams", "lobster"], preparation="fried", ingredients=["calamari", "ipswich clams", "lobster"], confidence=0.95),
            item("Maine Lobster Roll", section="Sandwiches", raw_description="Available hot with butter or cold with mayo (available with caviar). Served on toasted Iggy's brioche roll with sea salt fries.", raw_price_text="MKT", market_price=True, canonical_category="seafood", canonical_dish="LOBSTER_ROLL", protein=["lobster"], ingredients=["lobster", "brioche"], confidence=0.95),
            # Sides
            item("Sea Salt Fries", section="Sides", raw_price_text="9", price=9, canonical_category="sides", dietary_tags=["vegetarian"], confidence=0.94),
            item("Seasonal Vegetables", section="Sides", raw_price_text="12", price=12, canonical_category="sides", dietary_tags=["vegetarian"], seasonal=True, confidence=0.9),
            item("Neptune Toast", section="Sides", raw_price_text="11", price=11, canonical_category="sides", confidence=0.85),
            item("Wild Mushrooms", section="Sides", raw_price_text="14", price=14, canonical_category="sides", dietary_tags=["vegetarian"], ingredients=["mushroom"], confidence=0.9),
            item("Lobster Roe Slaw", section="Sides", raw_price_text="11", price=11, canonical_category="sides", protein=["lobster"], confidence=0.9),
            # Daily specials — Monday's has a published description (from the site's specials write-up); Tue-Sun are named on the site with no price or description shown.
            item("Lobster spaghettini", section="Daily Specials", raw_description="Monday special. Thin noodles in garlic, white wine, and tomato sauce with Maine lobster meat, breadcrumbs, and Parmesan.", canonical_category="pasta", canonical_dish="SEAFOOD_PASTA", protein=["lobster"], pasta_type="spaghettini", sauce="tomato white wine garlic", ingredients=["lobster", "garlic", "white wine", "tomato", "parmesan"], seasonal=True, confidence=0.8),
            item("Sea urchin bucatini", section="Daily Specials", raw_description="Tuesday special. No price or description published on the site beyond the name.", canonical_category="pasta", protein=["sea urchin"], pasta_type="bucatini", seasonal=True, confidence=0.5),
            item("Clams & bottarga", section="Daily Specials", raw_description="Wednesday special. No price or description published on the site beyond the name.", canonical_category="pasta", protein=["clams"], seasonal=True, confidence=0.5),
            item("Shrimp & grits", section="Daily Specials", raw_description="Thursday special. No price or description published on the site beyond the name.", canonical_category="seafood", protein=["shrimp"], seasonal=True, confidence=0.5),
            item("Squid ink risotto", section="Daily Specials", raw_description="Friday special. No price or description published on the site beyond the name.", canonical_category="seafood", protein=["squid"], seasonal=True, confidence=0.5),
            item("Paella Sarda", section="Daily Specials", raw_description="Saturday special. No price or description published on the site beyond the name.", canonical_category="seafood", seasonal=True, confidence=0.5),
            item("Lobster tacos", section="Daily Specials", raw_description="Sunday special. No price or description published on the site beyond the name.", canonical_category="seafood", protein=["lobster"], seasonal=True, confidence=0.5),
        ],
    },
    {
        "restaurant_id": "NE_0003",
        "name": "Pizzeria Regina",
        "slug": "pizzeria-regina",
        "address": "11 1/2 Thacher Street, Boston, MA 02113",
        "latitude": 42.36535,
        "longitude": -71.05695,
        "establishment_type": "pizzeria",
        "primary_cuisine": "pizza",
        "secondary_cuisines": "italian",
        "official_website": "https://pizzeriaregina.com/north_end.html",
        "official_menu_url": "https://reginapizzeria.com/assets/files/reg-NE-menu-426.pdf",
        "photo_url": "/restaurant-photos/pizzeria-regina.jpg",
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://reginapizzeria.com/assets/files/reg-NE-menu-426.pdf",
                "source_format": "pdf",
            }
        ],
        "extractor_model": "manual_seed_v2",
        "items": [
            item("Cheese Pizza", section="Regina Favorites", raw_description="The North End tradition. Secret 100-year-old dough, spicy-sweet Regina sauce, mozzarella.", raw_price_text="$17.50", price=17.5, canonical_category="pizza", canonical_dish="CHEESE_PIZZA", size="16 inch", ingredients=["tomato sauce", "mozzarella"], dietary_tags=["vegetarian"], confidence=0.96),
            item("Pepperoni Pizza", section="Regina Favorites", raw_price_text="$22", price=22, canonical_category="pizza", size="16 inch", protein=["pork"], ingredients=["tomato sauce", "mozzarella", "pepperoni"], confidence=0.96),
            item("The Giambotta", section="Regina Favorites", raw_description="Pepperoni, Regina sausage, salami, mushrooms, peppers, onions, fresh basil, mozzarella (anchovies upon request).", raw_price_text="$28", price=28, canonical_category="pizza", size="16 inch", protein=["pork"], ingredients=["pepperoni", "sausage", "salami", "mushroom", "peppers", "onions"], confidence=0.96),
            item("Melanzane", section="Regina Favorites", raw_description="House-made ricotta and marinara, oregano, house-made eggplant slices, red onions, basil, pecorino romano, mozzarella.", raw_price_text="$28", price=28, canonical_category="pizza", canonical_dish="EGGPLANT_PARMIGIANA", size="16 inch", dietary_tags=["vegetarian"], ingredients=["ricotta", "marinara", "eggplant", "onion", "basil"], confidence=0.96),
            item("St. Anthony's", section="Regina Favorites", raw_description="White pizza; Regina sausage, roasted onions and peppers, sausage links, parmesan, mozzarella, basil, garlic sauce.", raw_price_text="$28", price=28, canonical_category="pizza", canonical_dish="WHITE_PIZZA", size="16 inch", protein=["pork"], sauce="garlic", confidence=0.96),
            item("Buffalo Chicken", section="Regina Favorites", raw_description="Breaded buffalo chicken, spicy sauce, red onions, pepper jack blend, blue cheese drizzle.", raw_price_text="$28", price=28, canonical_category="pizza", size="16 inch", protein=["chicken"], confidence=0.96),
            item("Chicken Parmesan", section="Regina Favorites", raw_description="Marinara, hand-breaded chicken cutlets, mozzarella, parmesan, fresh basil.", raw_price_text="$28.25", price=28.25, canonical_category="pizza", size="16 inch", protein=["chicken"], sauce="marinara", confidence=0.96),
            item("Chicken and Prosciutto", section="Regina Favorites", raw_description="New. Regina pizza sauce, prosciutto, spinach, ricotta, breaded chicken cutlets, mozzarella, roasted red peppers, basil.", raw_price_text="$28.25", price=28.25, canonical_category="pizza", size="16 inch", protein=["chicken", "pork"], confidence=0.95),
            item("Margherita", section="Vegetarian", raw_description="Original Regina Pizza sauce, chopped basil, mozzarella, pecorino romano.", raw_price_text="$27", price=27, canonical_category="pizza", canonical_dish="MARGHERITA", size="16 inch", dietary_tags=["vegetarian"], ingredients=["tomato sauce", "basil", "mozzarella", "pecorino romano"], confidence=0.96),
            item("Vegetarian Primavera", section="Vegetarian", raw_description="White pizza; mozzarella, mushrooms, peppers, onions, black olives, basil, marinated tomatoes, artichoke hearts, garlic sauce.", raw_price_text="$27", price=27, canonical_category="pizza", canonical_dish="WHITE_PIZZA", size="16 inch", sauce="garlic", dietary_tags=["vegetarian"], ingredients=["mozzarella", "mushrooms", "peppers", "onions", "black olives", "basil", "tomato", "artichoke"], confidence=0.96),
            item("Quattro Formaggio", section="Vegetarian", raw_description="Mozzarella, ricotta, pecorino romano and parmesan sprinkled with fresh basil and Regina's garlic sauce.", raw_price_text="$27", price=27, canonical_category="pizza", canonical_dish="WHITE_PIZZA", size="16 inch", sauce="garlic", dietary_tags=["vegetarian"], ingredients=["mozzarella", "ricotta", "pecorino romano", "parmesan", "basil"], confidence=0.96),
            item("Mediterranean", section="Vegetarian", raw_description="Marinara, caramelized onions, roasted red peppers, black/green olives, red pepper flakes, parsley, capers, mozzarella, feta.", raw_price_text="$27", price=27, canonical_category="pizza", size="16 inch", dietary_tags=["vegetarian"], ingredients=["marinara", "caramelized onion", "roasted red pepper", "olives", "feta"], confidence=0.95),
            item("Farmers Market", section="Vegetarian", raw_description="Fresh spinach, feta, marinated artichokes and tomato, Regina pizza sauce, mozzarella.", raw_price_text="$27", price=27, canonical_category="pizza", size="16 inch", dietary_tags=["vegetarian"], ingredients=["spinach", "feta", "artichoke", "tomato"], confidence=0.95),
            item("Chicken Bacon Ranch", section="Meats", raw_description="New. Garlic sauce, grilled chicken, mozzarella, bacon, cherry tomatoes, ranch dressing.", raw_price_text="$27", price=27, canonical_category="pizza", size="16 inch", protein=["chicken", "pork"], sauce="garlic", confidence=0.95),
            item("Sausage Cacciatore", section="Meats", raw_description="Sliced sausage links, mushrooms, roasted onions and peppers, parsley, marinara, pecorino romano, mozzarella.", raw_price_text="$27", price=27, canonical_category="pizza", size="16 inch", protein=["pork"], confidence=0.95),
            item("Pollo Pesto", section="Meats", raw_description="Contains nuts. Pesto, grilled chicken breast, marinated tomatoes, ricotta, mozzarella, garlic sauce, basil.", raw_price_text="$27", price=27, canonical_category="pizza", size="16 inch", protein=["chicken"], sauce="pesto", ingredients=["pesto", "chicken", "tomato", "ricotta"], confidence=0.95),
            item("Meatlovers", section="Meats", raw_description="Pepperoni, ground sausage, Canadian bacon, Original Regina Pizza sauce, aged mozzarella.", raw_price_text="$27", price=27, canonical_category="pizza", size="16 inch", protein=["pork"], confidence=0.95),
            item("Capricciosa", section="Meats", raw_description="Sliced prosciutto, fresh mushrooms, ricotta, parmesan, mozzarella, Original Regina Pizza sauce.", raw_price_text="$27", price=27, canonical_category="pizza", size="16 inch", protein=["pork"], confidence=0.95),
            item("Pollo Regina", section="Meats", raw_description="Grilled chicken breast, ricotta, parmesan, pecorino romano, mozzarella, Regina pizza sauce, basil, roasted onions and peppers.", raw_price_text="$27", price=27, canonical_category="pizza", size="16 inch", protein=["chicken"], confidence=0.95),
            item("Meatball Pomodoro Fresco", section="Meats", raw_description="Marinated tomatoes, Regina meatballs, mozzarella, pecorino romano, parmesan, garlic sauce, basil.", raw_price_text="$27", price=27, canonical_category="pizza", size="16 inch", protein=["beef"], sauce="garlic", confidence=0.95),
            item("Italiano", section="Meats", raw_description="Original Regina Pizza sauce, pepperoni, artichoke hearts, mushrooms, mozzarella, parmesan.", raw_price_text="$27", price=27, canonical_category="pizza", size="16 inch", protein=["pork"], confidence=0.95),
            item("Prosciutto con Spinaci", section="Meats", raw_description="Original Regina Pizza sauce, ricotta, spinach, prosciutto, cherry tomatoes, mozzarella, pecorino romano, basil.", raw_price_text="$27", price=27, canonical_category="pizza", size="16 inch", protein=["pork"], confidence=0.95),
        ],
    },
    {
        "restaurant_id": "NE_0004",
        "name": "Modern Pastry",
        "slug": "modern-pastry",
        "address": "257 Hanover Street, Boston, MA 02113",
        "latitude": 42.36355,
        "longitude": -71.05445,
        "establishment_type": "bakery",
        "primary_cuisine": "bakery",
        "secondary_cuisines": "dessert,cafe",
        "official_website": "https://modernpastry.com/",
        "official_menu_url": "https://modernpastry.com/pages/pastry-list",
        "photo_url": "/restaurant-photos/modern-pastry.jpg",
        "sources": [
            {
                "menu_type": "bakery",
                "source_url": "https://modernpastry.com/pages/pastry-list",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v2",
        "items": [
            # Pastries — prices are never published on this page; left null, not invented.
            item("Cannoli", section="Pastries", raw_description="Made fresh to order. Shells: plain, chocolate dipped, chocolate covered, mini. Fillings: traditional ricotta, vanilla custard, chocolate custard, whipped cream, chantilly cream.", canonical_category="dessert", canonical_dish="CANNOLI", ingredients=["ricotta"], dietary_tags=["vegetarian"], confidence=0.97),
            item("Black & White", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Bomba", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Carrot Cake", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.93),
            item("Chocolate Ganache", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Chocolate Mousse", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Cream Puff", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.93),
            item("Creme Brulee", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.93),
            item("Eclair", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.93),
            item("French Horn", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.85),
            item("Fruit Tart", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.93),
            item("Key Lime Tart", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.93),
            item("Lemon Square", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Limoncello", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.88),
            item("Lobster Tail", section="Pastries", canonical_category="dessert", canonical_dish="LOBSTER_TAIL_PASTRY", dietary_tags=["vegetarian"], confidence=0.97),
            item("Mocha Mousse Roll", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.85),
            item("Napoleon", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Parigina", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.8),
            item("Peanut Butter Crunch", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.85),
            item("Ricotta Pie Slice", section="Pastries", canonical_category="dessert", canonical_dish="RICOTTA_PIE", dietary_tags=["vegetarian"], confidence=0.97),
            item("Rum Baba", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Rum Baba with Vanilla Cream", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Rum Savoy", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.85),
            item("Sfogliatella", section="Pastries", canonical_category="dessert", canonical_dish="SFOGLIATELLE", dietary_tags=["vegetarian"], confidence=0.97),
            item("Strawberry Cheesecake", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.93),
            item("Strawberry Shortcake", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.93),
            item("Tiramisu", section="Pastries", canonical_category="dessert", canonical_dish="TIRAMISU", dietary_tags=["vegetarian"], confidence=0.97),
            item("Triple Chocolate", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.85),
            item("Whoopie Pie", section="Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            # Cupcakes
            item("Vanilla Cupcake with Sprinkles", section="Cupcakes", raw_description='2.25"', canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Chocolate Cupcake with Sprinkles", section="Cupcakes", raw_description='2.25"', canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Boston Cupcake", section="Cupcakes", raw_description='3"', canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.88),
            item("Chocolate Peanut Butter Cupcake", section="Cupcakes", raw_description='3"', canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Flower Cupcake - Chocolate", section="Cupcakes", raw_description='3"', canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Flower Cupcake - Vanilla", section="Cupcakes", raw_description='3"', canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Hostess Cupcake", section="Cupcakes", raw_description='3"', canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.88),
            item("Red Velvet Cupcake", section="Cupcakes", raw_description='3"', canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            # Cookies
            item("Almond Tartlett", section="Cookies", canonical_category="dessert", ingredients=["almond"], dietary_tags=["vegetarian"], confidence=0.88),
            item("Colored Butter", section="Cookies", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.85),
            item("Champagne", section="Cookies", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.85),
            item("Chocolate Dipped - Apricot", section="Cookies", canonical_category="dessert", ingredients=["apricot"], dietary_tags=["vegetarian"], confidence=0.88),
            item("Chocolate Dipped - Nutella", section="Cookies", canonical_category="dessert", ingredients=["nutella"], dietary_tags=["vegetarian"], confidence=0.88),
            item("Chocolate Leaf (green) - Pistachio", section="Cookies", canonical_category="dessert", ingredients=["pistachio"], dietary_tags=["vegetarian"], confidence=0.85),
            item("Chocolate Leaf (red) - Strawberry", section="Cookies", canonical_category="dessert", ingredients=["strawberry"], dietary_tags=["vegetarian"], confidence=0.85),
            item("Rainbow (Petit Four)", section="Cookies", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.88),
            item("Raspberry Bowtie", section="Cookies", canonical_category="dessert", ingredients=["raspberry"], dietary_tags=["vegetarian"], confidence=0.85),
            item("Sable - Nutella", section="Cookies", canonical_category="dessert", ingredients=["nutella"], dietary_tags=["vegetarian"], confidence=0.85),
            item("Sable - Raspberry", section="Cookies", canonical_category="dessert", ingredients=["raspberry"], dietary_tags=["vegetarian"], confidence=0.85),
            item("Sesame", section="Cookies", canonical_category="dessert", ingredients=["sesame"], dietary_tags=["vegetarian"], confidence=0.85),
            item("Torroncini", section="Cookies", raw_description="Apricot, raspberry, or fig.", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.85),
            item("Wine", section="Cookies", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.85),
            # Other Cookies
            item("Almond Biscotti", section="Other Cookies", canonical_category="dessert", ingredients=["almond"], dietary_tags=["vegetarian"], confidence=0.9),
            item("Chocolate Dipped Almond Biscotti", section="Other Cookies", canonical_category="dessert", ingredients=["almond"], dietary_tags=["vegetarian"], confidence=0.9),
            item("Anise Biscotti", section="Other Cookies", canonical_category="dessert", ingredients=["anise"], dietary_tags=["vegetarian"], confidence=0.88),
            item("Amaretti", section="Other Cookies", raw_description="Italian almond macaroons.", canonical_category="dessert", ingredients=["almond"], dietary_tags=["vegetarian"], confidence=0.9),
            item("Amaretti w/ Pignoli", section="Other Cookies", raw_description="Almond macaroon with pine nuts.", canonical_category="dessert", ingredients=["almond", "pine nut"], dietary_tags=["vegetarian"], confidence=0.9),
            item("Pistachio Macaroon", section="Other Cookies", raw_description="Italian.", canonical_category="dessert", ingredients=["pistachio"], dietary_tags=["vegetarian"], confidence=0.88),
            item("French Macaron - Peanut Butter & Raspberry Jam", section="Other Cookies", canonical_category="dessert", ingredients=["peanut butter", "raspberry"], dietary_tags=["vegetarian"], confidence=0.88),
            item("French Macaron - Pistachio", section="Other Cookies", canonical_category="dessert", ingredients=["pistachio"], dietary_tags=["vegetarian"], confidence=0.88),
            item("French Macaron - Raspberry", section="Other Cookies", canonical_category="dessert", ingredients=["raspberry"], dietary_tags=["vegetarian"], confidence=0.88),
            item("French Macaron - Vanilla", section="Other Cookies", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.88),
            item("Florentine", section="Other Cookies", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.85),
            item("Elephant Ear", section="Other Cookies", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.85),
            item("Flat Tire", section="Other Cookies", raw_description="With raisins.", canonical_category="dessert", ingredients=["raisin"], dietary_tags=["vegetarian"], confidence=0.85),
            item("Gingerbread Man", section="Other Cookies", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.88),
            item("XL Chocolate Chip Cookie", section="Other Cookies", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("XL M&M's Cookie - Vanilla", section="Other Cookies", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.88),
            # Gluten-Free & Dairy-Free
            item("Whoopie Pie (GF & DF)", section="Gluten-Free & Dairy-Free", canonical_category="dessert", dietary_tags=["gluten-free", "vegetarian"], confidence=0.93),
            item("Chocolate Chip Cookie (GF & DF)", section="Gluten-Free & Dairy-Free", canonical_category="dessert", dietary_tags=["gluten-free", "vegetarian"], confidence=0.93),
            item("Coffee Cake (GF & DF)", section="Gluten-Free & Dairy-Free", canonical_category="dessert", dietary_tags=["gluten-free", "vegetarian"], confidence=0.9),
            item("Cannoli with Ricotta Filling (GF ONLY)", section="Gluten-Free & Dairy-Free", raw_description="Plain shell with ricotta filling only, no toppings.", canonical_category="dessert", canonical_dish="CANNOLI", ingredients=["ricotta"], dietary_tags=["gluten-free", "vegetarian"], confidence=0.95),
            # Breakfast Pastries
            item("Croissant - Plain", section="Breakfast Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Muffin - Blueberry", section="Breakfast Pastries", canonical_category="dessert", ingredients=["blueberry"], dietary_tags=["vegetarian"], confidence=0.9),
            item("Muffin - Corn", section="Breakfast Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Muffin - Cranberry & Walnut", section="Breakfast Pastries", canonical_category="dessert", ingredients=["cranberry", "walnut"], dietary_tags=["vegetarian"], confidence=0.9),
            item("Muffin - Pistachio", section="Breakfast Pastries", canonical_category="dessert", ingredients=["pistachio"], dietary_tags=["vegetarian"], confidence=0.88),
            item("Turnover - Apple", section="Breakfast Pastries", canonical_category="dessert", ingredients=["apple"], dietary_tags=["vegetarian"], confidence=0.9),
            item("Turnover - Blueberry", section="Breakfast Pastries", canonical_category="dessert", ingredients=["blueberry"], dietary_tags=["vegetarian"], confidence=0.9),
            item("Turnover - Raspberry", section="Breakfast Pastries", canonical_category="dessert", ingredients=["raspberry"], dietary_tags=["vegetarian"], confidence=0.9),
            item("Twists - Cinnamon", section="Breakfast Pastries", canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.9),
            item("Twists - Raspberry", section="Breakfast Pastries", canonical_category="dessert", ingredients=["raspberry"], dietary_tags=["vegetarian"], confidence=0.9),
        ],
    },
    {
        "restaurant_id": "NE_0005",
        "name": "Bricco",
        "slug": "bricco",
        "address": "241 Hanover Street, Boston, MA 02113",
        "latitude": 42.36332,
        "longitude": -71.05462,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "seafood,steak",
        "official_website": "https://bricco.com/",
        "official_menu_url": "https://bricco.com/menu/",
        "photo_url": "/restaurant-photos/bricco.jpg",
        "sources": [
            {
                # bricco.com/menu/ links 7 separate section pages (salad-soups,
                # signature-appetizers, briccos-artisanal-pasta, from-the-sea,
                # from-the-land, certified-angus-beef-chops, i-dolci) — this
                # records the landing page, not each item's exact sub-page.
                "menu_type": "dinner",
                "source_url": "https://bricco.com/menu/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v2",
        "items": [
            # Salad
            item("Caesar", section="Salad", raw_description="Blue sky bibb lettuce & radicchio, crispy ricotta polpette", raw_price_text="$15", price=15, canonical_category="salad", dietary_tags=["vegetarian"], confidence=0.95),
            item("Burrata", section="Salad", raw_description="Marinated roasted tomatoes, basil pesto, balsamic pearls, grilled ciabatta", raw_price_text="$24", price=24, canonical_category="salad", canonical_dish="BURRATA", dietary_tags=["vegetarian"], ingredients=["burrata", "tomato", "basil pesto"], confidence=0.95),
            item("Mozzarella di Bufala Caprese", section="Salad", raw_description="Colini tomatoes and basil pesto", raw_price_text="$21", price=21, canonical_category="salad", canonical_dish="CAPRESE", dietary_tags=["vegetarian"], ingredients=["buffalo mozzarella", "tomato", "basil pesto"], confidence=0.95),
            item("Insalata Mista", section="Salad", raw_description="Passion fruit purée, roasted pears, parmigiano cheese crostini & spicy pecans", raw_price_text="$16", price=16, canonical_category="salad", dietary_tags=["vegetarian"], confidence=0.95),
            # Signature Appetizers
            item("Charcuterie", section="Signature Appetizers", raw_description="Prosciutto, soppressata, mortadella, capocollo, formaggio, bruschetta, olives", raw_price_text="$28", price=28, canonical_category="antipasti", protein=["pork"], confidence=0.95),
            item("CAB Prime Beef Carpaccio", section="Signature Appetizers", raw_description="Arugula, parmigiano and truffle essence", raw_price_text="$24", price=24, canonical_category="antipasti", protein=["beef"], preparation="raw", confidence=0.95),
            item("Arancini", section="Signature Appetizers", raw_description="Sausage & broccolini, green arrabiata, parmesan aioli", raw_price_text="$22", price=22, canonical_category="antipasti", canonical_dish="ARANCINI", protein=["pork"], ingredients=["sausage", "broccolini", "arrabiata"], confidence=0.95),
            item("Octopus", section="Signature Appetizers", raw_description="Dry roasted with ginger & jalapeño crust with purple potato and string bean salad", raw_price_text="$24", price=24, canonical_category="seafood", canonical_dish="OCTOPUS", protein=["octopus"], preparation="roasted", ingredients=["octopus", "ginger", "jalapeño", "potato"], confidence=0.95),
            item("Zucchini Flowers", section="Signature Appetizers", raw_description="Stuffed with truffle ricotta cheese, tempura, grilled vegetables", raw_price_text="$21", price=21, canonical_category="antipasti", dietary_tags=["vegetarian"], ingredients=["zucchini flower", "truffle ricotta"], confidence=0.95),
            item("1/2 Dozen Oysters", section="Signature Appetizers", raw_description="On half shell with cocktail sauce & champagne mignonette", raw_price_text="$24", price=24, canonical_category="seafood", canonical_dish="OYSTERS", protein=["oyster"], preparation="raw", portion="half dozen", confidence=0.95),
            item("Eggplant Baked", section="Signature Appetizers", raw_description="Layered with bufala mozzarella, tomato coulis, eggplant pellini", raw_price_text="$19", price=19, canonical_category="italian_american", canonical_dish="EGGPLANT_PARMIGIANA", dietary_tags=["vegetarian"], ingredients=["eggplant", "buffalo mozzarella", "tomato"], confidence=0.95),
            item("Steak Tartare", section="Signature Appetizers", raw_description="Cab prime, dijon, capers, cornichons, truffle aioli, quail egg, chips", raw_price_text="$28", price=28, canonical_category="antipasti", protein=["beef"], preparation="raw", confidence=0.95),
            item("Jumbo Shrimp Scampi", section="Signature Appetizers", raw_description="Seared with lemon, cherry tomatoes, potato gratin", raw_price_text="$24", price=24, canonical_category="seafood", protein=["shrimp"], sauce="scampi", confidence=0.95),
            item("Meatballs", section="Signature Appetizers", raw_description="CAB Prime, served with fresh ricotta & crostini", raw_price_text="$21", price=21, canonical_category="italian_american", canonical_dish="MEATBALLS", protein=["beef"], ingredients=["beef", "ricotta"], confidence=0.95),
            item("Frittura Mista", section="Signature Appetizers", raw_description="Calamari, scallops, shrimp, fried onion strings & tartar dip", raw_price_text="$24", price=24, canonical_category="seafood", canonical_dish="CALAMARI", protein=["calamari", "scallop", "shrimp"], preparation="fried", confidence=0.95),
            # Artisanal Pasta
            item("Spinach Fettuccine", section="Artisanal Pasta", raw_description="Truffle besciamella, shaved black truffles", raw_price_text="$32", price=32, canonical_category="pasta", pasta_type="fettuccine", sauce="truffle bechamel", ingredients=["spinach", "truffle", "besciamella"], dietary_tags=["vegetarian"], confidence=0.95),
            item("Spaghettoni al Pomodoro", section="Artisanal Pasta", raw_description="San Marzano tomatoes, fresh basil, shaved parmigiana", raw_price_text="$29", price=29, canonical_category="pasta", canonical_dish="POMODORO", pasta_type="spaghettoni", sauce="pomodoro", ingredients=["san marzano tomato", "basil", "parmigiano"], dietary_tags=["vegetarian"], confidence=0.95),
            item("Ricotta Pillows", section="Artisanal Pasta", raw_description="Dressed with truffle butter, wild mushrooms, gnudi di ricotta garnish", raw_price_text="$32", price=32, canonical_category="pasta", pasta_type="gnudi", sauce="truffle butter", dietary_tags=["vegetarian"], confidence=0.93),
            item("Pappardelle al Cinghiale", section="Artisanal Pasta", raw_description="Wild boar braised in red wine with porcini mushrooms", raw_price_text="$34", price=34, canonical_category="pasta", pasta_type="pappardelle", protein=["boar"], ingredients=["wild boar", "red wine", "porcini"], confidence=0.95),
            item("Agnollotti al Plin", section="Artisanal Pasta", raw_description="Braised veal and beef stuffing with ricotta, spinach, truffle cream", raw_price_text="$32", price=32, canonical_category="pasta", pasta_type="agnolotti", sauce="truffle cream", protein=["veal", "beef"], confidence=0.93),
            item("Garganelli Amatriciana", section="Artisanal Pasta", raw_description="Niman Ranch pancetta, spicy Colino tomato, pecorino romano", raw_price_text="$29", price=29, canonical_category="pasta", canonical_dish="AMATRICIANA", pasta_type="garganelli", sauce="amatriciana", protein=["pork"], ingredients=["pancetta", "tomato", "pecorino romano"], confidence=0.95),
            item("Short Rib Fazoletti", section="Artisanal Pasta", raw_description="Cognac, shallot, dijon demi, balsamic pearl", raw_price_text="$32", price=32, canonical_category="pasta", pasta_type="fazzoletti", protein=["beef"], confidence=0.93),
            item("Chittarrine Jumbo Shrimp", section="Artisanal Pasta", raw_description="Zucchini, limoncello, peperoncino", raw_price_text="$34", price=34, canonical_category="pasta", canonical_dish="SEAFOOD_PASTA", pasta_type="chitarrine", protein=["shrimp"], ingredients=["shrimp", "zucchini", "limoncello", "peperoncino"], confidence=0.95),
            item("Tortelli Pumpkin", section="Artisanal Pasta", raw_description="Amaretti & honey, sage butter, root vegetables, ricotta salata", raw_price_text="$31", price=31, canonical_category="pasta", canonical_dish="SQUASH_RAVIOLI", pasta_type="tortelli", sauce="sage butter", ingredients=["pumpkin", "amaretti", "honey", "sage", "ricotta salata"], dietary_tags=["vegetarian"], confidence=0.95),
            item("Gnocchetti Sorrentina", section="Artisanal Pasta", raw_description="Baked with bufala mozzarella, tomatoes, basil", raw_price_text="$29", price=29, canonical_category="pasta", pasta_type="gnocchi", ingredients=["bufala mozzarella", "tomato", "basil"], dietary_tags=["vegetarian"], confidence=0.95),
            item("Farfalle Tartufate", section="Artisanal Pasta", raw_description="Lobster meat, fava beans, pancetta, black truffle, lobster fumét", raw_price_text="$34", price=34, canonical_category="pasta", canonical_dish="SEAFOOD_PASTA", pasta_type="farfalle", protein=["lobster", "pork"], ingredients=["lobster", "fava beans", "pancetta", "black truffle", "lobster fumet"], confidence=0.95),
            item("Risotto", section="Artisanal Pasta", raw_description="Chef's daily special", raw_price_text="MKT", market_price=True, canonical_category="pasta", pasta_type="risotto", seasonal=True, confidence=0.85),
            # From the Sea
            item("Ora King Salmon", section="From the Sea", raw_description="Pesto salsa verde, fregola, sun dried tomatoes, potato and leak puree", raw_price_text="$39", price=39, canonical_category="seafood", protein=["salmon"], confidence=0.95),
            item("Chilean Sea Bass in Agrodolce", section="From the Sea", raw_description="Baby bok choy, herbed potato gallette, carrot fondue", raw_price_text="$52", price=52, canonical_category="seafood", protein=["sea bass"], confidence=0.95),
            item("Mediterranean Branzino", section="From the Sea", raw_description="Roasted herb potatoes, baby spinach, pinzimonio sauce", raw_price_text="$49", price=49, canonical_category="seafood", protein=["branzino"], ingredients=["branzino", "potato", "spinach"], confidence=0.95),
            item("Bricco's Brodetto", section="From the Sea", raw_description="Half lobster, shrimp, swordfish, monkfish, calamari, Wellfleet clams and mussels, Colino tomatoes, fish fumet, grilled asparagus, bruschette", raw_price_text="$59", price=59, canonical_category="seafood", canonical_dish="CIOPPINO", protein=["lobster", "shrimp", "swordfish", "monkfish", "calamari", "clams", "mussels"], confidence=0.95),
            item("Rare-Seared Ahi Tuna", section="From the Sea", raw_description="Black & white sesame seed encrusted, Japanese eggplant marinated with white wine vinaigrette, roasted red peppers, snow peas, spinach, black olives, ginger soy dip", raw_price_text="$46", price=46, canonical_category="seafood", protein=["tuna"], preparation="seared", confidence=0.95),
            # From the Land
            item("7-Spice Murray's Brick Chicken", section="From the Land", raw_description="7-spice marinated half chicken, crispy parmesan potatoes, herbed butter reduction", raw_price_text="$39", price=39, canonical_category="meat", protein=["chicken"], confidence=0.93),
            item("Mallard Duck Duetto", section="From the Land", raw_description="Seared breast, sweet potato smash, maitake mushroom, sweet & sour soy sauce", raw_price_text="$49", price=49, canonical_category="meat", protein=["duck"], confidence=0.93),
            item("Veal Ossobuco, Marcho Farms", section="From the Land", raw_description="Traditional saffron risotto, sautéed spinach", raw_price_text="$47", price=47, canonical_category="meat", protein=["veal"], confidence=0.95),
            item("Sam Adam's Braised Pork Shank", section="From the Land", raw_description="Slowly braised, arborio cacio e pepe risotto, shaved truffle", raw_price_text="$44", price=44, canonical_category="meat", protein=["pork"], preparation="braised", confidence=0.93),
            item("Veal Valdostana", section="From the Land", raw_description="Fontina & pancetta stuffed veal chop, yukon gold potato twice baked with oyster mushrooms", raw_price_text="$64", price=64, canonical_category="meat", protein=["veal", "pork"], confidence=0.93),
            item("Braised Beef Short Ribs", section="From the Land", raw_description="Creamy parmigiano polenta, roasted chestnuts, red wine reduction, sweet Italian glaze", raw_price_text="$46", price=46, canonical_category="meat", protein=["beef"], preparation="braised", confidence=0.95),
            # Certified Angus Beef & Chops
            item("8oz Prime Filet Mignon", section="Certified Angus Beef & Chops", raw_description="21-day aged — gentle, luxurious flavor", raw_price_text="$56", price=56, canonical_category="steak", protein=["beef"], size="8 oz", confidence=0.95),
            item("12oz Prime Filet Mignon", section="Certified Angus Beef & Chops", raw_description="21-day aged — gentle, luxurious flavor", raw_price_text="$66", price=66, canonical_category="steak", protein=["beef"], size="12 oz", confidence=0.95),
            item("22oz Prime Bone-in NY Sirloin", section="Certified Angus Beef & Chops", raw_description="35-day dry aged — bold, rich, nutty flavor", raw_price_text="$78", price=78, canonical_category="steak", protein=["beef"], size="22 oz", confidence=0.95),
            item("16oz Grass Fed Rib Eye", section="Certified Angus Beef & Chops", raw_description="Niman Ranch, tender bite, rich flavor", raw_price_text="$82", price=82, canonical_category="steak", protein=["beef"], size="16 oz", confidence=0.95),
            item("24oz Prime Bone-in Cowboy Ribeye", section="Certified Angus Beef & Chops", raw_description="35-day aged, tender bite, rich flavor", raw_price_text="$88", price=88, canonical_category="steak", protein=["beef"], size="24 oz", confidence=0.95),
            item("36oz Prime Tomahawk Ribeye (For Two)", section="Certified Angus Beef & Chops", raw_description="35-day dry aged, tender bite, rich flavor", raw_price_text="MKT", market_price=True, canonical_category="steak", protein=["beef"], size="36 oz", portion="for two", confidence=0.9),
            item("Veal Chop", section="Certified Angus Beef & Chops", raw_description="Catelli Brothers, milk fed", raw_price_text="$62", price=62, canonical_category="steak", protein=["veal"], confidence=0.95),
            item("Colorado Rack of Lamb", section="Certified Angus Beef & Chops", raw_description="Dijon, herb crust, Superior Farms, pasture raised", raw_price_text="$78", price=78, canonical_category="steak", protein=["lamb"], confidence=0.95),
            item("Baby Brussels Sprouts", section="Certified Angus Beef & Chops (Sides)", raw_description="Pancetta & sweet black balsamic", raw_price_text="$16", price=16, canonical_category="sides", protein=["pork"], confidence=0.93),
            item("Lobster Gnocchi", section="Certified Angus Beef & Chops (Sides)", raw_price_text="$22", price=22, canonical_category="sides", protein=["lobster"], confidence=0.9),
            item("Hand-cut Italian Fries", section="Certified Angus Beef & Chops (Sides)", raw_price_text="$13", price=13, canonical_category="sides", dietary_tags=["vegetarian"], confidence=0.93),
            item("Double Mashed Potatoes", section="Certified Angus Beef & Chops (Sides)", raw_price_text="$13", price=13, canonical_category="sides", dietary_tags=["vegetarian"], confidence=0.93),
            item("Roasted Baby Carrots", section="Certified Angus Beef & Chops (Sides)", raw_price_text="$14", price=14, canonical_category="sides", dietary_tags=["vegetarian"], confidence=0.93),
            item("Parmesan Creamed Spinach", section="Certified Angus Beef & Chops (Sides)", raw_price_text="$14", price=14, canonical_category="sides", dietary_tags=["vegetarian"], confidence=0.93),
            item("Jumbo Asparagus", section="Certified Angus Beef & Chops (Sides)", raw_price_text="$16", price=16, canonical_category="sides", dietary_tags=["vegetarian"], confidence=0.93),
            item("Roasted Wild Mushrooms", section="Certified Angus Beef & Chops (Sides)", raw_price_text="$16", price=16, canonical_category="sides", dietary_tags=["vegetarian"], confidence=0.93),
            item("Spicy Sautéed Broccoli Rabe", section="Certified Angus Beef & Chops (Sides)", raw_price_text="$16", price=16, canonical_category="sides", dietary_tags=["vegetarian"], confidence=0.93),
            # I Dolci
            item("Bricco's Signature Bread Pudding", section="I Dolci", raw_description="Vanilla bean bread pudding, caramelized banana & vanilla gelato", raw_price_text="$17", price=17, canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.95),
            item("Cuore Caldo al Chocolate", section="I Dolci", raw_description="Warm chocolate cake with molten center and hazelnut gelato", raw_price_text="$17", price=17, canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.95),
            item("Crème Brûlée", section="I Dolci", raw_description="Fiocchi di frolla cookies", raw_price_text="$15", price=15, canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.95),
            item("Chocolate Mousse Opera Cake", section="I Dolci", raw_description="Layered hazelnut sponge cake, milk chocolate glaze, crunchy pearl", raw_price_text="$17", price=17, canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.95),
            item("Blueberry Cheesecake", section="I Dolci", raw_description="Homemade cake with white chocolate sauce", raw_price_text="$16", price=16, canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.95),
            item("Drink That Espresso Martini Tiramisú", section="I Dolci", raw_description="Lady fingers soaked in espresso martini and mascarpone cream", raw_price_text="$19", price=19, canonical_category="dessert", canonical_dish="TIRAMISU", ingredients=["ladyfingers", "espresso martini", "mascarpone"], dietary_tags=["vegetarian"], confidence=0.96),
            item("Homemade Gelato Trio", section="I Dolci", raw_description="Trio of flavors: chocolate, vanilla, hazelnut", raw_price_text="$14", price=14, canonical_category="dessert", ingredients=["gelato"], dietary_tags=["vegetarian"], confidence=0.95),
            item("Homemade Sorbetto Trio", section="I Dolci", raw_description="Trio of flavors: lemon, mango, passionfruit", raw_price_text="$14", price=14, canonical_category="dessert", dietary_tags=["vegetarian", "gluten-free"], confidence=0.95),
            item("Three Perfect Cheeses", section="I Dolci", raw_description="Crostini, fig preserves", raw_price_text="$26", price=26, canonical_category="dessert", dietary_tags=["vegetarian"], confidence=0.95),
        ],
    },
]
