"""Highest-value next wave: NE_0031..NE_0045.

Hand-researched 2026-08-28 from each restaurant's own site when a priced
menu was published. Items without a published price stay null. Beverages
are excluded, matching seed_data.py.
"""

from __future__ import annotations

from typing import Any

from app.seed_data import item

WAVE2_RESTAURANTS: list[dict[str, Any]] = [
    {
        "restaurant_id": "NE_0031",
        "name": "Galleria Umberto",
        "slug": "galleria-umberto",
        "address": "289 Hanover Street, Boston, MA 02113",
        "latitude": 42.3637590,
        "longitude": -71.0543860,
        "establishment_type": "counter_service",
        "primary_cuisine": "pizza",
        "secondary_cuisines": "italian",
        "official_website": None,
        "official_menu_url": None,
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 4, 5], "open": "10:45", "close": "14:30"},
        ],
        "sources": [
            {
                "menu_type": "lunch",
                "source_url": "https://maps.google.com/?q=Galleria+Umberto+289+Hanover+Boston",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_in_store_menu_no_website",
        "items": [
            item("Sicilian Pizza Slice", section="Counter", raw_description="Thick square Sicilian slice with tomato sauce and cheese. Cash only; sells out.", canonical_category="pizza", canonical_dish="CHEESE_PIZZA", portion="slice", dietary_tags=["vegetarian"], confidence=0.9),
            item("Pizzette", section="Counter", raw_description="Smaller round pizza.", canonical_category="pizza", canonical_dish="CHEESE_PIZZA", portion="pizzette", dietary_tags=["vegetarian"], confidence=0.85),
            item("Arancini", section="Counter", raw_description="Large fried rice ball with meat, peas, tomato sauce, and cheese.", canonical_category="antipasti", canonical_dish="ARANCINI", protein=["beef"], ingredients=["rice", "peas", "tomato sauce", "cheese"], preparation="fried", confidence=0.9),
            item("Panzarotti", section="Counter", raw_description="Fried mashed-potato ball with a cheese center.", canonical_category="antipasti", ingredients=["potato", "mozzarella"], preparation="fried", dietary_tags=["vegetarian"], confidence=0.88),
            item("Panini", section="Counter", raw_description="Hot panini from the lunch counter.", canonical_category="italian_american", confidence=0.7),
            item("Spinach and Cheese Calzone", section="Calzones", canonical_category="pizza", ingredients=["spinach", "cheese"], dietary_tags=["vegetarian"], confidence=0.85),
            item("Spinach, Cheese and Sausage Calzone", section="Calzones", protein=["pork"], ingredients=["spinach", "cheese", "sausage"], confidence=0.85),
            item("Ricotta, Ham and Salami Calzone", section="Calzones", protein=["pork"], ingredients=["ricotta", "ham", "salami"], confidence=0.85),
        ],
    },
    {
        "restaurant_id": "NE_0032",
        "name": "Lucia Ristorante",
        "slug": "lucia-ristorante",
        "address": "415 Hanover Street, Boston, MA 02113",
        "latitude": 42.3655906,
        "longitude": -71.0527209,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "seafood",
        "official_website": "https://luciab.st/",
        "official_menu_url": "https://luciab.st/main-menu",
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 6], "open": "11:00", "close": "22:00"},
            {"days": [4, 5], "open": "11:00", "close": "22:30"},
        ],
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://luciab.st/main-menu",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_official_hours_image_menu",
        "items": [
            item("Carrozza", section="Antipasti", raw_description="Breaded fried mozzarella stuffed with prosciutto, topped with marinara.", canonical_category="antipasti", protein=["pork"], ingredients=["mozzarella", "prosciutto", "marinara"], preparation="fried", confidence=0.82),
            item("Chitarra al Tartufo", section="Pasta", raw_description="Abruzzese chitarra with mushrooms, sausage, and white truffle cream.", canonical_category="pasta", pasta_type="chitarra", protein=["pork"], sauce="white truffle cream", ingredients=["mushroom", "sausage", "truffle"], confidence=0.82),
            item("Guazzetto di Mare", section="Pasta", raw_description="Seafood medley in tomato sauce over pappardelle.", canonical_category="pasta", canonical_dish="FRUTTI_DI_MARE", pasta_type="pappardelle", protein=["seafood"], sauce="tomato", confidence=0.8),
            item("Gnocchi Abruzzese", section="Pasta", canonical_category="pasta", canonical_dish="GNOCCHI", pasta_type="gnocchi", confidence=0.75),
            item("Maccheroni Amatriciana", section="Pasta", canonical_category="pasta", canonical_dish="AMATRICIANA", pasta_type="maccheroni", sauce="amatriciana", confidence=0.8),
            item("Chicken Parmigiana", section="Secondi", canonical_category="italian_american", canonical_dish="CHICKEN_PARMIGIANA", protein=["chicken"], confidence=0.75),
            item("Veal Parmigiana", section="Secondi", canonical_category="italian_american", canonical_dish="VEAL_PARMIGIANA", protein=["veal"], confidence=0.75),
            item("Tiramisu", section="Dolci", canonical_category="dessert", canonical_dish="TIRAMISU", confidence=0.75),
        ],
    },
    {
        "restaurant_id": "NE_0033",
        "name": "Strega by Nick Varano",
        "slug": "strega-by-nick-varano",
        "address": "379 Hanover Street, Boston, MA 02113",
        "latitude": 42.3649606,
        "longitude": -71.0530139,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "steakhouse",
        "official_website": "https://stregabynickvarano.com/",
        "official_menu_url": "https://stregabynickvarano.com/dinner/",
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2], "open": "16:00", "close": "22:00"},
            {"days": [3, 4], "open": "12:00", "close": "23:00"},
            {"days": [5], "open": "11:00", "close": "23:00"},
            {"days": [6], "open": "11:00", "close": "14:30"},
        ],
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://stregabynickvarano.com/dinner/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_official_hours_js_menu",
        "items": [
            item("Mamma's Famous Meatball", section="Dinner", raw_description="Award-winning meatball; a Strega signature.", canonical_category="italian_american", canonical_dish="MEATBALLS", confidence=0.78),
            item("Rigatoni Alla Vodka", section="Dinner", raw_description="Spicy rigatoni alla vodka prepared tableside in a wheel of cheese.", canonical_category="pasta", pasta_type="rigatoni", sauce="vodka", confidence=0.8),
            item("Chicken Parmigiana", section="Dinner", canonical_category="italian_american", canonical_dish="CHICKEN_PARMIGIANA", protein=["chicken"], confidence=0.72),
            item("Calamari Fritti", section="Dinner", canonical_category="seafood", canonical_dish="CALAMARI", protein=["calamari"], preparation="fried", confidence=0.72),
            item("Surf and Turf", section="Dinner", canonical_category="meat", protein=["beef", "lobster"], confidence=0.7),
            item("Tiramisu", section="Dolci", canonical_category="dessert", canonical_dish="TIRAMISU", confidence=0.7),
        ],
    },
    {
        "restaurant_id": "NE_0034",
        "name": "Tresca",
        "slug": "tresca",
        "address": "233 Hanover Street, Boston, MA 02113",
        "latitude": 42.3630121,
        "longitude": -71.0550862,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "mediterranean",
        "official_website": "https://trescanorthend.com/",
        "official_menu_url": "https://trescanorthend.com/",
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 4], "open": "17:00", "close": "22:00"},
            {"days": [5, 6], "open": "16:00", "close": "22:00"},
        ],
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://trescanorthend.com/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_official_homepage_favorites",
        "items": [
            item("Anna Maria's Famous Stuffed Meatballs", section="Favorite Dishes", raw_description="Ground veal and sirloin, cipollini onions, fire roasted peppers, fresh mozzarella, tomato basil sauce, grilled focaccia, whipped ricotta", canonical_category="italian_american", canonical_dish="MEATBALLS", protein=["veal", "beef"], ingredients=["cipollini onions", "roasted peppers", "mozzarella", "tomato basil sauce", "focaccia", "ricotta"], confidence=0.95),
            item("Ray Bourque Special", section="Favorite Dishes", raw_description="Veal Chop Parmesan served with a side of Pasta Bolognese", canonical_category="italian_american", canonical_dish="VEAL_PARMIGIANA", protein=["veal"], confidence=0.94),
            item("Black Truffle Ricotta Gnocchi", section="Favorite Dishes", raw_description="House made ricotta gnocchi, wild mushroom ragu, spinach", canonical_category="pasta", canonical_dish="GNOCCHI", pasta_type="gnocchi", ingredients=["ricotta gnocchi", "wild mushroom ragu", "spinach", "black truffle"], confidence=0.95),
            item("Linguine with Clams", section="Pasta", canonical_category="pasta", pasta_type="linguine", protein=["clams"], confidence=0.7),
            item("Calamari", section="Antipasti", canonical_category="seafood", canonical_dish="CALAMARI", protein=["calamari"], confidence=0.7),
        ],
    },
    {
        "restaurant_id": "NE_0035",
        "name": "Arya Trattoria",
        "slug": "arya-trattoria",
        "address": "253 Hanover Street, Boston, MA 02113",
        "latitude": 42.3631954,
        "longitude": -71.0547841,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "seafood",
        "official_website": "https://aryatrattoria.com/",
        "official_menu_url": "https://aryatrattoria.com/menu/",
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 6], "open": "17:00", "close": "22:00"},
            {"days": [4, 5], "open": "17:00", "close": "22:30"},
        ],
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://aryatrattoria.com/menu/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_official_dine_in_menu",
        "items": [
            item("Gamberi con Limoncello", section="Antipasti", raw_description="Limoncello marinated shrimp with garlic, pine nuts, capers, and grilled salted lemon", raw_price_text="$19", price=19, canonical_category="seafood", protein=["shrimp"], ingredients=["limoncello", "garlic", "pine nuts", "capers", "lemon"], confidence=0.96),
            item("Calamari Fritti", section="Antipasti", raw_description="Locally caught crispy calamari with pickled chili peppers and smokey tomato vinaigrette", raw_price_text="$16", price=16, canonical_category="seafood", canonical_dish="CALAMARI", protein=["calamari"], ingredients=["pickled chili peppers", "tomato vinaigrette"], preparation="fried", confidence=0.96),
            item("Mamma Rosalie's Meatballs", section="Antipasti", raw_description="Award winning Boston's Best meatballs, San Marzano tomato sauce", raw_price_text="$16", price=16, canonical_category="italian_american", canonical_dish="MEATBALLS", sauce="san marzano tomato", confidence=0.96),
            item("Torta di Melanzane", section="Antipasti", raw_description="Baked layered eggplant, fresh mozzarella, San Marzano tomato", raw_price_text="$16", price=16, canonical_category="italian_american", canonical_dish="EGGPLANT_PARMIGIANA", ingredients=["eggplant", "mozzarella", "san marzano tomato"], dietary_tags=["vegetarian"], confidence=0.92),
            item("Insalata Caprese", section="Insalate", raw_description="Imported Bufala mozzarella, heirloom local tomato, basil, basil infused EVOO", raw_price_text="$20", price=20, canonical_category="salad", canonical_dish="CAPRESE", ingredients=["bufala mozzarella", "tomato", "basil"], dietary_tags=["vegetarian"], confidence=0.96),
            item("Rigatoni Pesto con Burrata", section="Arya's Signature Pasta", raw_description="Handmade rigatoni pasta, Clay's famous pesto sauce, house made pancetta, fresh Burrata", raw_price_text="$34", price=34, canonical_category="pasta", canonical_dish="PESTO", pasta_type="rigatoni", sauce="pesto", protein=["pancetta"], ingredients=["burrata"], confidence=0.96),
            item("Bolognese da Abruzzo", section="Arya's Signature Pasta", raw_description="Handmade tagliatelle pasta prepared with a typical Abruzzese style veal and beef ragout, enriched with pancetta and tomato", raw_price_text="$36", price=36, canonical_category="pasta", canonical_dish="BOLOGNESE", pasta_type="tagliatelle", protein=["veal", "beef", "pancetta"], sauce="bolognese", confidence=0.96),
            item("Gnocchi con Aragosta", section="Arya's Signature Pasta", raw_description="Handmade potato gnocchi tossed with truffle and fontina cheese fonduta, and the meat of 1¼ pound Maine lobster, tomato lobster broth and asparagus", raw_price_text="$42", price=42, canonical_category="pasta", canonical_dish="GNOCCHI", pasta_type="gnocchi", protein=["lobster"], ingredients=["truffle", "fontina", "lobster", "asparagus"], confidence=0.96),
            item("Ravioli con Funghi", section="Arya's Signature Pasta", raw_description="Handmade oyster mushroom ravioli, truffled mascarpone, grilled escarole", raw_price_text="$34", price=34, canonical_category="pasta", canonical_dish="RAVIOLI", pasta_type="ravioli", ingredients=["oyster mushroom", "truffled mascarpone", "escarole"], dietary_tags=["vegetarian"], confidence=0.94),
            item("Spaghetti con Vongole", section="Arya's Signature Pasta", raw_description="Locally harvested Cape Cod littleneck clams, garlic, dry white wine, fresh oregano", raw_price_text="$30", price=30, canonical_category="pasta", pasta_type="spaghetti", protein=["clams"], ingredients=["garlic", "white wine", "oregano"], confidence=0.96),
            item("Frutti di Mare Fra Diavolo", section="Arya's Signature Pasta", raw_description="Handmade tagliatelle tossed with local lobster, Cape Cod littleneck clams, scallops, and shrimp finished in a spicy white wine San Marzano tomato broth", raw_price_text="M.P.", market_price=True, canonical_category="pasta", canonical_dish="FRUTTI_DI_MARE", pasta_type="tagliatelle", protein=["lobster", "clams", "scallops", "shrimp"], sauce="fra diavolo", confidence=0.95),
            item("Osso Buco di Maiale", section="Secondi", raw_description="Tender 4-hour braised pork shank in a rich tomato sauce with crispy polenta", raw_price_text="$36", price=36, canonical_category="meat", protein=["pork"], ingredients=["tomato sauce", "polenta"], confidence=0.96),
            item("The Parm", section="Secondi", raw_description="Murray's farm organic chicken breast topped with San Marzano tomato sauce, mozzarella cheese baked in the oven with rigatoni pomodoro", raw_price_text="$35", price=35, canonical_category="italian_american", canonical_dish="CHICKEN_PARMIGIANA", protein=["chicken"], pasta_type="rigatoni", confidence=0.95),
            item("Bistecca Delmonico", section="Secondi", raw_description="16oz bone in ribeye, Arya made truffle fries with a red wine porcini mushroom glaze", raw_price_text="$50", price=50, canonical_category="meat", protein=["beef"], size="16oz", ingredients=["truffle fries", "porcini"], confidence=0.95),
        ],
    },
    {
        "restaurant_id": "NE_0036",
        "name": "The Red Fox",
        "slug": "the-red-fox",
        "address": "326 Commercial Street, Boston, MA 02113",
        "latitude": 42.3653192,
        "longitude": -71.0512635,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "seafood",
        "official_website": "https://redfoxnorthend.com/",
        "official_menu_url": "https://redfoxnorthend.com/menus/",
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 6], "open": "17:00", "close": "22:00"},
            {"days": [4, 5], "open": "17:00", "close": "23:00"},
        ],
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://redfoxnorthend.com/menus/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_official_dinner_menu",
        "items": [
            item("Tuna Crudo", section="Antipasti", raw_description="Lemon, olive oil, chili", raw_price_text="$22", price=22, canonical_category="seafood", protein=["tuna"], ingredients=["lemon", "olive oil", "chili"], confidence=0.96),
            item("Prosciutto & Zeppole", section="Antipasti", raw_description="Honey", raw_price_text="$24", price=24, canonical_category="antipasti", protein=["pork"], ingredients=["prosciutto", "zeppole", "honey"], confidence=0.96),
            item("Arancini", section="Antipasti", raw_description="Mozzarella, pomodoro", raw_price_text="$18", price=18, canonical_category="antipasti", canonical_dish="ARANCINI", ingredients=["mozzarella", "pomodoro"], dietary_tags=["vegetarian"], confidence=0.95),
            item("Meatballs", section="Antipasti", raw_description="Red sauce, basil", raw_price_text="$19", price=19, canonical_category="italian_american", canonical_dish="MEATBALLS", sauce="red sauce", ingredients=["basil"], confidence=0.96),
            item("Lobster Fra Diavolo", section="Pasta", raw_price_text="$36", price=36, canonical_category="pasta", protein=["lobster"], sauce="fra diavolo", confidence=0.95),
            item("Orecchiette with Pistachio Pesto", section="Pasta", raw_description="With pistachio pesto", raw_price_text="$26", price=26, canonical_category="pasta", canonical_dish="PESTO", pasta_type="orecchiette", sauce="pistachio pesto", dietary_tags=["vegetarian"], confidence=0.94),
            item("Linguine Con Vongole", section="Pasta", raw_price_text="$28", price=28, canonical_category="pasta", pasta_type="linguine", protein=["clams"], confidence=0.96),
            item("Rigatoni Alla Vodka", section="Pasta", raw_price_text="$26", price=26, canonical_category="pasta", pasta_type="rigatoni", sauce="vodka", confidence=0.96),
            item("Bolognese", section="Pasta", raw_price_text="$28", price=28, canonical_category="pasta", canonical_dish="BOLOGNESE", sauce="bolognese", confidence=0.96),
            item("Lasagna", section="Red Sauce Classics", raw_description="Ragu, ricotta. For two.", raw_price_text="$58", price=58, canonical_category="pasta", pasta_type="lasagna", portion="for two", ingredients=["ragu", "ricotta"], confidence=0.95),
            item("Spaghetti & Meatballs", section="Red Sauce Classics", raw_price_text="$28", price=28, canonical_category="pasta", canonical_dish="MEATBALLS", pasta_type="spaghetti", confidence=0.96),
            item("Chicken Parm", section="Red Sauce Classics", raw_price_text="$32", price=32, canonical_category="italian_american", canonical_dish="CHICKEN_PARMIGIANA", protein=["chicken"], confidence=0.96),
            item("Eggplant Parm", section="Red Sauce Classics", raw_price_text="$30", price=30, canonical_category="italian_american", canonical_dish="EGGPLANT_PARMIGIANA", dietary_tags=["vegetarian"], confidence=0.96),
            item("Red Fox Parm", section="Secondi", raw_description="Chicken cutlets stuffed with prosciutto, fontina, topped with mozzarella, red sauce, parm, arugula", raw_price_text="$38", price=38, canonical_category="italian_american", canonical_dish="CHICKEN_PARMIGIANA", protein=["chicken", "pork"], ingredients=["prosciutto", "fontina", "mozzarella", "arugula"], confidence=0.94),
            item("Risotto Frutti Di Mare", section="Secondi", raw_description="Lobster, clams, mussels, shrimp", raw_price_text="$44", price=44, canonical_category="seafood", canonical_dish="FRUTTI_DI_MARE", protein=["lobster", "clams", "mussels", "shrimp"], confidence=0.96),
            item("Branzino", section="Secondi", raw_description="Roasted Mediterranean sea bass with fregula, salsa verde, parsley salad", raw_price_text="$36", price=36, canonical_category="seafood", protein=["branzino"], ingredients=["fregola", "salsa verde"], confidence=0.96),
        ],
    },
    {
        "restaurant_id": "NE_0037",
        "name": "Tony & Elaine's",
        "slug": "tony-and-elaines",
        "address": "111 North Washington Street, Boston, MA 02113",
        "latitude": 42.3655857,
        "longitude": -71.0581314,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "italian_american",
        "official_website": "https://www.tonyandelaines.com/",
        "official_menu_url": "https://www.tonyandelaines.com/menu",
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 6], "open": "11:30", "close": "22:00"},
            {"days": [4, 5], "open": "11:30", "close": "23:00"},
        ],
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://www.tonyandelaines.com/menu",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_official_menu",
        "items": [
            item("Caprese", section="Salads", raw_description="Burrata, tomatoes", raw_price_text="13.95", price=13.95, canonical_category="salad", canonical_dish="CAPRESE", ingredients=["burrata", "tomato"], dietary_tags=["vegetarian"], confidence=0.96),
            item("Meatball Grinder", section="Sandwiches", raw_description="The meatballs, mozzarella", raw_price_text="12.95", price=12.95, canonical_category="italian_american", canonical_dish="MEATBALLS", ingredients=["meatballs", "mozzarella"], confidence=0.96),
            item("Italian Coldcut Grinder", section="Sandwiches", raw_description="Provolone, oil, vinegar, giardiniera", raw_price_text="12.95", price=12.95, canonical_category="italian_american", ingredients=["provolone", "giardiniera"], confidence=0.95),
            item("Arancini", section="Appetizers", raw_description="Fontina, marinara", raw_price_text="9.95", price=9.95, canonical_category="antipasti", canonical_dish="ARANCINI", ingredients=["fontina", "marinara"], dietary_tags=["vegetarian"], confidence=0.95),
            item("The Meatballs", section="Appetizers", raw_description="Grandma's meatballs, red sauce", raw_price_text="9.95", price=9.95, canonical_category="italian_american", canonical_dish="MEATBALLS", sauce="red sauce", confidence=0.96),
            item("Calamari", section="Appetizers", raw_description="Sweet hot peppers, marinara", raw_price_text="13.95", price=13.95, canonical_category="seafood", canonical_dish="CALAMARI", protein=["calamari"], ingredients=["hot peppers", "marinara"], confidence=0.96),
            item("Cacio e Pepe", section="Pasta", raw_description="Spaghetti, black pepper, parmesan", raw_price_text="16.95", price=16.95, canonical_category="pasta", canonical_dish="CACIO_E_PEPE", pasta_type="spaghetti", dietary_tags=["vegetarian"], confidence=0.96),
            item("Spaghetti & Meatballs", section="Pasta", raw_description="Spaghetti, grandma's meatballs", raw_price_text="17.95", price=17.95, canonical_category="pasta", canonical_dish="MEATBALLS", pasta_type="spaghetti", confidence=0.96),
            item("Pasta Alla Vodka", section="Pasta", raw_description="Rigatoni, marinara, vodka, pancetta", raw_price_text="15.95", price=15.95, canonical_category="pasta", pasta_type="rigatoni", sauce="vodka", protein=["pancetta"], confidence=0.96),
            item("Lobster Ravioli", section="Pasta", raw_description="Maine lobster, marsala wine cream", raw_price_text="27.95", price=27.95, canonical_category="pasta", canonical_dish="LOBSTER_RAVIOLI", pasta_type="ravioli", protein=["lobster"], sauce="marsala cream", confidence=0.96),
            item("Bolognese", section="Pasta", raw_description="Pappardelle, meat gravy, parmesan", raw_price_text="19.95", price=19.95, canonical_category="pasta", canonical_dish="BOLOGNESE", pasta_type="pappardelle", confidence=0.96),
            item("Chicken Parmesan", section="Entrees", raw_description="Rigatoni, mozzarella, basil", raw_price_text="22.95", price=22.95, canonical_category="italian_american", canonical_dish="CHICKEN_PARMIGIANA", protein=["chicken"], pasta_type="rigatoni", confidence=0.96),
            item("Veal Parmesan", section="Entrees", raw_description="Rigatoni, mozzarella, basil", raw_price_text="24.95", price=24.95, canonical_category="italian_american", canonical_dish="VEAL_PARMIGIANA", protein=["veal"], confidence=0.96),
            item("Eggplant Parmesan", section="Entrees", raw_description="Rigatoni, mozzarella, basil", raw_price_text="17.95", price=17.95, canonical_category="italian_american", canonical_dish="EGGPLANT_PARMIGIANA", dietary_tags=["vegetarian"], confidence=0.96),
        ],
    },
    {
        "restaurant_id": "NE_0038",
        "name": "Table",
        "slug": "table",
        "address": "445 Hanover Street, Boston, MA 02113",
        "latitude": 42.3661366,
        "longitude": -71.0526131,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": None,
        "official_website": "https://www.tableboston.com/",
        "official_menu_url": "https://www.tableboston.com/",
        "photo_url": None,
        "hours": [
            {"days": [2, 3], "open": "19:00", "close": "22:00"},
            {"days": [4, 5], "open": "18:00", "close": "22:30"},
            {"days": [6], "open": "15:30", "close": "21:00"},
        ],
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://www.tableboston.com/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_official_prix_fixe",
        "items": [
            item("Prix Fixe Dinner", section="Dinner", raw_description="Shared plates with your party only. Wednesday–Saturday.", raw_price_text="$138", price=138, canonical_category="italian_american", portion="prix fixe per seat", confidence=0.95),
            item("Sunday Supper", section="Dinner", raw_description="Prix fixe Sunday supper.", raw_price_text="$98", price=98, canonical_category="italian_american", portion="prix fixe per seat", confidence=0.95),
            item("A La Carte Four Courses", section="Dinner", raw_description="Four courses. Wednesday thru Friday only. Parties of 2-3.", raw_price_text="$75", price=75, canonical_category="italian_american", portion="four courses per person", confidence=0.94),
        ],
    },
    {
        "restaurant_id": "NE_0039",
        "name": "Little Sage",
        "slug": "little-sage",
        "address": "352 Hanover Street, Boston, MA 02113",
        "latitude": 42.3651141,
        "longitude": -71.0533835,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "pasta",
        "official_website": "https://www.littlesageboston.com/",
        "official_menu_url": "https://www.littlesageboston.com/menus/",
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 6], "open": "17:00", "close": "21:30"},
            {"days": [4, 5], "open": "17:00", "close": "22:00"},
        ],
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://www.littlesageboston.com/menus/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_official_dinner_menu",
        "items": [
            item("Tomato Bruschetta, Whipped Ricotta", section="Per Tavola", raw_price_text="14", price=14, canonical_category="antipasti", dietary_tags=["vegetarian"], ingredients=["tomato", "ricotta"], confidence=0.95),
            item("Spanish Octopus, Potatoes, Sweet Baby Peppers", section="Antipasti", raw_price_text="22", price=22, canonical_category="seafood", canonical_dish="OCTOPUS", protein=["octopus"], ingredients=["potato", "peppers"], confidence=0.96),
            item("Burrata, Zucchini, Snap Pea, & Herb Salad", section="Antipasti", raw_description="Toasted pine nuts", raw_price_text="23", price=23, canonical_category="salad", canonical_dish="BURRATA", ingredients=["burrata", "zucchini", "snap peas", "pine nuts"], dietary_tags=["vegetarian"], confidence=0.96),
            item("Bucatini ala Gricia", section="House Made Pasta", raw_description="Leoncini pancetta, black pepper, pecorino pepato", raw_price_text="27", price=27, canonical_category="pasta", pasta_type="bucatini", protein=["pancetta"], ingredients=["pecorino"], confidence=0.96),
            item("Ricotta Gnocchi, Maine Lobster", section="House Made Pasta", raw_description="Smoked butter, cherry tomato, marjoram", raw_price_text="34", price=34, canonical_category="pasta", canonical_dish="GNOCCHI", pasta_type="gnocchi", protein=["lobster"], ingredients=["smoked butter", "cherry tomato"], confidence=0.96),
            item("Casarecce, Herb Pesto", section="House Made Pasta", raw_description="Asparagus, pistachio stracciatella", raw_price_text="27", price=27, canonical_category="pasta", canonical_dish="PESTO", pasta_type="casarecce", sauce="pesto", ingredients=["asparagus", "pistachio", "stracciatella"], dietary_tags=["vegetarian"], confidence=0.95),
            item("Paccheri, Veal & Porcini Bolognese", section="House Made Pasta", raw_description="Grana Padano", raw_price_text="29", price=29, canonical_category="pasta", canonical_dish="BOLOGNESE", pasta_type="paccheri", protein=["veal"], ingredients=["porcini", "grana padano"], confidence=0.96),
            item("Tagliolini, Crab", section="House Made Pasta", raw_description="Bomba Pugliese, lemon, fennel pollen", raw_price_text="34", price=34, canonical_category="pasta", pasta_type="tagliolini", protein=["crab"], ingredients=["lemon", "fennel pollen"], confidence=0.96),
            item("Corn Tortelli", section="House Made Pasta", raw_description="Butter, basil, cherry tomatoes", raw_price_text="28", price=28, canonical_category="pasta", pasta_type="tortelli", ingredients=["corn", "butter", "basil", "cherry tomatoes"], dietary_tags=["vegetarian"], confidence=0.95),
            item("Baked Fazzoletti Pasta", section="Al Forno", raw_description="Short rib, spinach & fontina, cherry tomatoes", raw_price_text="29", price=29, canonical_category="pasta", pasta_type="fazzoletti", protein=["beef"], ingredients=["short rib", "spinach", "fontina"], confidence=0.95),
            item("Giannone Chicken", section="Al Forno", raw_description="Crushed potatoes, brown butter & sage", raw_price_text="30", price=30, canonical_category="meat", protein=["chicken"], ingredients=["potato", "brown butter", "sage"], confidence=0.95),
            item("Local Striped Bass", section="Al Forno", raw_description="Roasted garlic butter, snap peas, grilled corn, cherry tomatoes", raw_price_text="36", price=36, canonical_category="seafood", protein=["striped bass"], confidence=0.95),
        ],
    },
    {
        "restaurant_id": "NE_0040",
        "name": "Parla",
        "slug": "parla",
        "address": "230 Hanover Street, Boston, MA 02113",
        "latitude": 42.3632161,
        "longitude": -71.0552193,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "italian",
        "secondary_cuisines": "mediterranean",
        "official_website": "https://www.parlaboston.com/",
        "official_menu_url": "https://www.parlaboston.com/",
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3], "open": "16:30", "close": "21:00"},
            {"days": [4, 5], "open": "16:30", "close": "21:30"},
            {"days": [6], "open": "10:00", "close": "21:00"},
        ],
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://www.parlaboston.com/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_official_homepage",
        "items": [
            item("Carbonara", section="Dinner", raw_description="Named on Parla's official site as part of the kitchen's range.", canonical_category="pasta", canonical_dish="CARBONARA", confidence=0.7),
            item("Ceviche", section="Dinner", canonical_category="seafood", protein=["fish"], confidence=0.65),
            item("Chicken and Waffles", section="Brunch", canonical_category="meat", protein=["chicken"], confidence=0.7),
        ],
    },
    {
        "restaurant_id": "NE_0041",
        "name": "Sunny Girl",
        "slug": "sunny-girl",
        "address": "252 Commercial Street, Boston, MA 02113",
        "latitude": 42.3636758,
        "longitude": -71.0514676,
        "establishment_type": "counter_service",
        "primary_cuisine": "american",
        "secondary_cuisines": "breakfast",
        "official_website": "https://www.sunnygirlboston.com/",
        "official_menu_url": "https://www.sunnygirlboston.com/",
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 4], "open": "07:00", "close": "14:00"},
            {"days": [5, 6], "open": "07:00", "close": "16:00"},
        ],
        "sources": [
            {
                "menu_type": "lunch",
                "source_url": "https://www.sunnygirlboston.com/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_official_sandwich_menu",
        "items": [
            item("The OG", section="Morning Starters", raw_description="Fried Nellie's egg, American cheese, sunny sauce, housemade English muffin", raw_price_text="$7", price=7, canonical_category="american", protein=["egg"], confidence=0.96),
            item("BGC (Breakfast Grilled Cheese)", section="Morning Starters", raw_description="Over-easy Nellie's egg, North Country smokehouse bacon, cheddar, fontina, gruyère, béchamel, Iggy's focaccia", raw_price_text="$12.5", price=12.5, canonical_category="american", protein=["egg", "pork"], confidence=0.96),
            item("Artie Party", section="Morning Starters", raw_description="Over-easy Nellie's egg, crispy mortadella, pistachio mascarpone, wild cherry mostarda, housemade English muffin", raw_price_text="$11.5", price=11.5, canonical_category="american", protein=["egg", "pork"], confidence=0.96),
            item("Sunny Girl", section="Morning Starters", raw_description="Fried Nellie's egg, bacon, cheddar, smashed avocado, sunny sauce, housemade English muffin", raw_price_text="$10", price=10, canonical_category="american", protein=["egg", "pork"], confidence=0.96),
            item("Truffle Shuffle", section="Morning Starters", raw_description="Over-easy Nellie's egg, black truffle pecorino, burrata, tomato conserva, basil gremolata, pancetta, Iggy's focaccia", raw_price_text="$14.5", price=14.5, canonical_category="american", protein=["egg", "pork"], ingredients=["truffle pecorino", "burrata", "pancetta"], confidence=0.96),
            item("The Lox", section="Morning Starters", raw_description="Ducktrap smoked salmon, everything mascarpone, confit fennel, citrus salad, housemade English muffin", raw_price_text="$14", price=14, canonical_category="seafood", protein=["salmon"], confidence=0.96),
            item("Croque Madame", section="Morning Starters", raw_description="Sunny-side-up Nellie's egg, rosemary cotto ham, gruyère, pecorino toscano, smoked mozzarella, béchamel, Iggy's sourdough", raw_price_text="$14", price=14, canonical_category="american", protein=["egg", "pork"], confidence=0.96),
            item("Breakfast Torta", section="Morning Starters", raw_description="Chorizo migas, cheddar, refried black beans, avocado salsa, smashed avocado, Iggy's seeded roll", raw_price_text="$13.5", price=13.5, canonical_category="mexican", protein=["pork", "egg"], confidence=0.95),
            item("(Pre-'98) Italian", section="Lunch Favorites", raw_description="Salame, soppressata, mortadella, burrata, provolone, roasted tomato pesto, shaved iceberg, Calabrian chili hots, Iggy's sub roll", raw_price_text="$15", price=15, canonical_category="italian_american", protein=["pork"], confidence=0.96),
            item("Sunny Girl BLT", section="Lunch Favorites", raw_description="North Country smokehouse bacon, lettuce, tomato, sunny sauce, Iggy's sourdough", raw_price_text="$13.5", price=13.5, canonical_category="american", protein=["pork"], confidence=0.96),
            item("Verde", section="Lunch Favorites", raw_description="Rapini a la plancha, black truffle pecorino, marinated roasted tomatoes, garlic confit, lemon EVOO, Iggy's sub roll", raw_price_text="$13.5", price=13.5, canonical_category="american", dietary_tags=["vegetarian"], confidence=0.95),
        ],
    },
    {
        "restaurant_id": "NE_0042",
        "name": "Tenoch Mexican",
        "slug": "tenoch-mexican",
        "address": "3 Lewis Street, Boston, MA 02113",
        "latitude": 42.3632757,
        "longitude": -71.0518746,
        "establishment_type": "counter_service",
        "primary_cuisine": "mexican",
        "secondary_cuisines": None,
        "official_website": "https://www.tenochmexican.com/",
        "official_menu_url": "https://www.tenochmexican.com/",
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 4, 5, 6], "open": "11:00", "close": "21:00"},
        ],
        "sources": [
            {
                "menu_type": "lunch",
                "source_url": "https://www.tenochmexican.com/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_official_menu_unpriced",
        "items": [
            item("Torta Asada", section="Tortas", raw_description="Steak with melted cheese, cilantro, jalapeños", canonical_category="mexican", protein=["beef"], confidence=0.93),
            item("Torta Campechana", section="Tortas", raw_description="Chorizo, carnitas (pork)", canonical_category="mexican", protein=["pork"], confidence=0.93),
            item("Torta Tenoch", section="Tortas", raw_description="Carnitas (pork), slice of ham", canonical_category="mexican", protein=["pork"], confidence=0.93),
            item("Torta Choriqueso", section="Tortas", raw_description="Chorizo with melted Oaxaca cheese, lettuce", canonical_category="mexican", protein=["pork"], confidence=0.93),
            item("Torta Pastor", section="Tortas", raw_description="Pork in achiote sauce, cilantro, pineapple", canonical_category="mexican", protein=["pork"], confidence=0.93),
            item("Torta Vegetales", section="Tortas", raw_description="Roasted vegetables", canonical_category="mexican", dietary_tags=["vegetarian"], confidence=0.9),
            item("Torta Pescado", section="Tortas", raw_description="Fish, lettuce, cucumber, cilantro", canonical_category="mexican", protein=["fish"], confidence=0.93),
            item("Taco Carnitas", section="Tacos", raw_description="Maciza pork", canonical_category="mexican", protein=["pork"], confidence=0.93),
            item("Taco Asada con Queso", section="Tacos", raw_description="Steak with melted cheese", canonical_category="mexican", protein=["beef"], confidence=0.93),
            item("Taco Pescado", section="Tacos", raw_description="Fish with chipotle, cucumber, chipotle mayo", canonical_category="mexican", protein=["fish"], confidence=0.93),
            item("Taco Carne Asada", section="Tacos", raw_description="Steak", canonical_category="mexican", protein=["beef"], confidence=0.93),
            item("Enchiladas", section="Plates", raw_description="Verde or mole. Two filled corn tortillas topped with salsa, queso fresco, and sour cream. Served with rice and beans.", canonical_category="mexican", confidence=0.9),
        ],
    },
    {
        "restaurant_id": "NE_0043",
        "name": "Theo's Cozy Corner",
        "slug": "theos-cozy-corner",
        "address": "162 Salem Street, Boston, MA 02113",
        "latitude": 42.3660875,
        "longitude": -71.0551103,
        "establishment_type": "counter_service",
        "primary_cuisine": "american",
        "secondary_cuisines": "brazilian",
        "official_website": None,
        "official_menu_url": None,
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 4, 5, 6], "open": "07:00", "close": "15:00"},
        ],
        "sources": [
            {
                "menu_type": "lunch",
                "source_url": "https://maps.google.com/?q=Theo%27s+Cozy+Corner+162+Salem+Boston",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_no_website_named_dishes",
        "items": [
            item("Moqueca", section="Brazilian", raw_description="Brazilian seafood stew.", canonical_category="seafood", protein=["fish", "shellfish"], confidence=0.7),
            item("Fried Tilapia", section="Brazilian", canonical_category="seafood", protein=["tilapia"], preparation="fried", confidence=0.7),
            item("Picanha Steak", section="Brazilian", raw_description="When available.", canonical_category="meat", protein=["beef"], seasonal=True, confidence=0.65),
            item("Eggs and Home Fries", section="Breakfast", canonical_category="american", protein=["egg"], confidence=0.65),
        ],
    },
    {
        "restaurant_id": "NE_0044",
        "name": "Bricco Salumeria & Pasta Shop",
        "slug": "bricco-salumeria",
        "address": "11 Board Alley, Boston, MA 02113",
        "latitude": 42.3629299,
        "longitude": -71.0549759,
        "establishment_type": "counter_service",
        "primary_cuisine": "italian",
        "secondary_cuisines": "sandwich",
        "official_website": "https://bricco.com/",
        "official_menu_url": "https://bricco.com/",
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 4, 5], "open": "10:00", "close": "18:00"},
            {"days": [6], "open": "10:00", "close": "16:00"},
        ],
        "sources": [
            {
                "menu_type": "lunch",
                "source_url": "https://bricco.com/",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_counter_sandwiches",
        "items": [
            item("Chicken Parmigiano Sandwich", section="Sandwiches", raw_description="Chicken cutlet, provolone, basil, red sauce; hot or cold.", canonical_category="italian_american", canonical_dish="CHICKEN_PARMIGIANA", protein=["chicken"], confidence=0.8),
            item("Grilled Zucchini Sandwich", section="Sandwiches", raw_description="Grilled zucchini, marinated eggplant, shaved Parmigiano, arugula, roasted red pepper on focaccia.", canonical_category="italian_american", dietary_tags=["vegetarian"], ingredients=["zucchini", "eggplant", "parmigiano", "arugula", "roasted red pepper", "focaccia"], confidence=0.8),
            item("Italian Cold Cut Sandwich", section="Sandwiches", canonical_category="italian_american", protein=["pork"], confidence=0.7),
            item("Fresh Tagliatelle", section="Pasta Shop", canonical_category="pasta", pasta_type="tagliatelle", confidence=0.7),
        ],
    },
    {
        "restaurant_id": "NE_0045",
        "name": "Quattro",
        "slug": "quattro",
        "address": "264 Hanover Street, Boston, MA 02113",
        "latitude": 42.3636546,
        "longitude": -71.0548061,
        "establishment_type": "full_service_restaurant",
        "primary_cuisine": "pizza",
        "secondary_cuisines": "italian",
        "official_website": None,
        "official_menu_url": None,
        "photo_url": None,
        "hours": [
            {"days": [0, 1, 2, 3, 4, 6], "open": "16:00", "close": "21:30"},
            {"days": [5], "open": "11:00", "close": "21:30"},
        ],
        "sources": [
            {
                "menu_type": "dinner",
                "source_url": "https://maps.google.com/?q=Quattro+264+Hanover+Boston",
                "source_format": "html",
            }
        ],
        "extractor_model": "manual_seed_v5_neapolitan_identity",
        "items": [
            item("Margherita Pizza", section="Pizza", raw_description="Neapolitan-style pie from the Hanover Street brick oven.", canonical_category="pizza", canonical_dish="MARGHERITA", size="whole", dietary_tags=["vegetarian"], confidence=0.75),
            item("Quattro Formaggi Pizza", section="Pizza", canonical_category="pizza", canonical_dish="WHITE_PIZZA", size="whole", dietary_tags=["vegetarian"], confidence=0.7),
            item("Rotisserie Chicken", section="Mains", raw_description="Chicken from the in-house rotisserie.", canonical_category="meat", protein=["chicken"], confidence=0.7),
            item("Meatballs", section="Antipasti", canonical_category="italian_american", canonical_dish="MEATBALLS", confidence=0.65),
        ],
    },
]
